import {blessingsFor} from '@/lib/blessings';
import {denyWrite} from '@/lib/authorization';
import { database, portraits } from '@/lib/storage';
import { importPortrait, PortraitImportError } from '@/lib/portrait-import';
export const dynamic = 'force-dynamic';
// Public reads; every mutation requires the platform-authenticated owner.
export async function GET() {try { const rows=await database().prepare('SELECT * FROM heroes ORDER BY month IS NULL, month, name').all();return Response.json(rows.results);}catch(e){console.error(e);return Response.json({error:'Your schedule could not be loaded. Please try again.'},{status:503});}}
export async function POST(request:Request){
 const denied=denyWrite(request);if(denied)return denied;
 if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});
 let uploaded:string|null=null;
 try{const f=await request.formData();const id=String(f.get('id')||crypto.randomUUID()),name=String(f.get('name')||'').trim(),title=String(f.get('title')||'').trim(),category=String(f.get('category')),color=String(f.get('color')),status=String(f.get('status')),month=String(f.get('month')||'')||null,notes=String(f.get('notes')||'').trim(),schedule=String(f.get('schedule')||'General'),blessing=category==='Emblem'?null:String(f.get('blessing')||'')||null;
 if(blessingsFor(category).length&&(!blessing||!blessingsFor(category).includes(blessing)))return Response.json({error:'Select a blessing for this hero type.'},{status:400});
 if(schedule==='Monthly Revival'&&!['Legendary','Mythic'].includes(category))return Response.json({error:'Monthly Revival supports Legendary and Mythic heroes.'},{status:400});
 if(!['General','Remix','Monthly Revival'].includes(schedule)||!name||name.length>100||title.length>150||notes.length>2000||!['Legendary','Mythic','Emblem','Chosen Hero'].includes(category)||!['Red','Blue','Green','Colorless'].includes(color)||!['Confirmed','Predicted','Uncertain','Unknown'].includes(status)||(month&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))||(status!=='Unknown'&&!month))return Response.json({error:'Check the name, category, and rerun month.'},{status:400});
 const old=await database().prepare('SELECT portrait FROM heroes WHERE id=?').bind(id).first<{portrait:string|null}>();let portrait=old?.portrait||null;let file=f.get('portrait');
 const portraitUrl=String(f.get('portraitUrl')||'').trim();
 if(portraitUrl&&!(file instanceof File&&file.size)){const imported=await importPortrait(portraitUrl);file=new File([imported.bytes as BlobPart],'imported-portrait',{type:imported.contentType});}
 if(file instanceof File&&file.size){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>3145728)return Response.json({error:'Choose a PNG, JPG, or WebP under 3 MB.'},{status:400});const bytes=new Uint8Array(await file.arrayBuffer());const valid=file.type==='image/png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71:file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!valid)return Response.json({error:'Invalid portrait image.'},{status:400});uploaded=crypto.randomUUID();await portraits().put(uploaded,bytes,{httpMetadata:{contentType:file.type}});portrait=uploaded;}
 await database().prepare('INSERT INTO heroes (id,name,title,category,color,month,status,notes,portrait,updated,blessing,schedule) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,title=excluded.title,category=excluded.category,color=excluded.color,month=excluded.month,status=excluded.status,notes=excluded.notes,portrait=excluded.portrait,updated=excluded.updated,blessing=excluded.blessing,schedule=excluded.schedule').bind(id,name,title,category,color,status==='Unknown'?null:month,status,notes,portrait,new Date().toISOString(),blessing,schedule).run();if(uploaded&&old?.portrait)await portraits().delete(old.portrait).catch(console.error);return Response.json({ok:true});
 }catch(e){console.error(e);if(uploaded)await portraits().delete(uploaded).catch(console.error);if(e instanceof PortraitImportError)return Response.json({error:e.message},{status:400});return Response.json({error:'Could not save the hero or import its portrait. Your entries are still in the form. Please try again.'},{status:503});}}
export async function DELETE(request:Request){
 const denied=denyWrite(request);if(denied)return denied;if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});try{const {id}=await request.json() as {id?:unknown};if(typeof id!=='string')return Response.json({error:'Invalid hero'},{status:400});const old=await database().prepare('SELECT portrait FROM heroes WHERE id=?').bind(id).first<{portrait:string|null}>();await database().prepare('DELETE FROM heroes WHERE id=?').bind(id).run();if(old?.portrait)await portraits().delete(old.portrait).catch(console.error);return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:'Could not delete this hero.'},{status:503});}}


