import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {handleCommunity,protect,imageType,validatePost,extractFlair} from './community.mjs';
import flairs from '../lib/community-flairs.json' with {type:'json'};
function setup(){
 const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./community-schema.sql',import.meta.url),'utf8'));
 const DB={prepare:sql=>({bind:(...values)=>{
  const args=values.map(v=>v instanceof ArrayBuffer?new Uint8Array(v):v);
  return {
   first:async()=>db.prepare(sql).get(...args)||null,
   all:async()=>({results:db.prepare(sql).all(...args)}),
   run:async()=>({meta:{changes:Number(db.prepare(sql).run(...args).changes)}})
  };
 }})};
 return {GITHUB_CLIENT_SECRET:'test-secret',HEAD_ADMIN_GITHUB_ID:'101106225',SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'test-key',DB,db};
}
const owner={github_id:'101106225',website_id:'site-owner',login:'clustifle',role:'owner',website_account:true,can_vote:true};
const voter={github_id:'123',website_id:'site-voter',login:'member',role:'voter',website_account:true,can_vote:true};
const headers={'Content-Type':'application/json','Cache-Control':'no-store'};
async function request(env,path,body,u=voter,method=body?'POST':'GET'){return handleCommunity(new Request('https://service.test/community'+path,{method,headers:{Authorization:'Bearer test','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env,{user:async()=>u,rate:async()=>{},headers});}
async function connection(env,u,publicReads=0){env.db.prepare('INSERT INTO community_connections VALUES(?,?,?,?,?,?)').run(u.github_id,u.website_id,u.login,await protect(env,'token-that-must-never-be-returned',u.github_id),publicReads,new Date().toISOString());}
const mockFetch=fn=>{const old=globalThis.fetch;globalThis.fetch=fn;return()=>globalThis.fetch=old;};
test('the eleven requested flairs persist in GitHub Markdown and strip cleanly for website display',()=>{assert.deepEqual(flairs.map(f=>f.name),['Quick Question','Serious Discussion','News','Analysis','Chat','Unit Showcase','Memes','Resource','Gameplay','Aether Showcase','New Hero Idea']);const p=validatePost({title:'FEH chat',body:'**A thought**',flair:'memes'});assert.ok(p.body.includes('**Flair: Memes**'));assert.deepEqual(extractFlair(p.body),{flair:'memes',body:'**A thought**'});assert.throws(()=>validatePost({title:'FEH chat',body:'Hello',flair:'art-fan-art'}));});
test('anonymous users cannot post, connect, or upload pictures',async()=>{const e=setup();for(const path of ['/posts','/connect','/images'])assert.equal((await request(e,path,{},null)).status,401);e.db.close();});
test('post limits and executable image types are rejected',()=>{assert.throws(()=>validatePost({title:'a',body:'hello'}));assert.throws(()=>validatePost({title:'Valid',body:'a'.repeat(20001)}));assert.deepEqual(validatePost({title:' Heroes ',body:' **Marth** '}),{title:'Heroes',body:'**Marth**'});assert.equal(imageType(new TextEncoder().encode('<svg onload="alert(1)">')),null);assert.equal(imageType(new Uint8Array([255,216,255,0])),'image/jpeg');});
test('GitHub connection requires a website username and the linked GitHub identity',async()=>{const e=setup();let profiles=[];const restore=mockFetch(async url=>new Response(JSON.stringify(String(url).includes('tracker_profiles')?profiles:{id:999,login:'other'}),{headers:{'Content-Type':'application/json','x-oauth-scopes':'public_repo'}}));try{assert.equal((await request(e,'/connect',{token:'x'.repeat(30)})).status,403);profiles=[{username:'member'}];assert.equal((await request(e,'/connect',{token:'x'.repeat(30)})).status,403);assert.equal(e.db.prepare('SELECT COUNT(*) AS n FROM community_connections').get().n,0);}finally{restore();e.db.close();}});
test('connections are encrypted and ordinary members cannot enable the public reader',async()=>{const e=setup();const restore=mockFetch(async url=>new Response(JSON.stringify(String(url).includes('tracker_profiles')?[{username:'member'}]:String(url).includes('/user')?{id:123,login:'member'}:{data:{viewer:{login:'member'},repository:{isPrivate:false,hasDiscussionsEnabled:true}}}),{headers:{'Content-Type':'application/json','x-oauth-scopes':'public_repo'}}));try{assert.equal((await request(e,'/connect',{token:'x'.repeat(30),publicReads:true})).status,403);assert.equal((await request(e,'/connect',{token:'x'.repeat(30)})).status,200);assert.ok(!e.db.prepare('SELECT encrypted_token FROM community_connections').get().encrypted_token.includes('x'.repeat(30)));assert.ok(!(await (await request(e,'/session')).text()).includes('encrypted_token'));}finally{restore();e.db.close();}});
test('public reads hide owner viewer permissions and moderated comment bodies',async()=>{const e=setup();await connection(e,owner,1);const restore=mockFetch(async()=>new Response(JSON.stringify({data:{repository:{isPrivate:false,hasDiscussionsEnabled:true,discussion:{id:'d',number:1,body:'Public post',viewerCanUpdate:true,viewerHasUpvoted:true,comments:{nodes:[{body:'hidden private spam',isMinimized:true,viewerCanDelete:true}]}}}}}),{headers:{'Content-Type':'application/json'}}));try{const r=await request(e,'/posts/1',undefined,null),data=await r.json();assert.equal(r.status,200);assert.equal(data.post.viewerCanUpdate,false);assert.equal(data.post.viewerHasUpvoted,false);assert.equal(data.post.comments.nodes[0].viewerCanDelete,false);assert.ok(!JSON.stringify(data).includes('hidden private spam'));assert.ok(!e.db.prepare('SELECT payload FROM community_cache').get().payload.includes('hidden private spam'));}finally{restore();e.db.close();}});
test('members cannot edit another author or reply to a different repository discussion',async()=>{const e=setup();await connection(e,voter);let mutations=0;const restore=mockFetch(async(_url,init)=>{const q=JSON.parse(init.body).query;if(q.startsWith('mutation'))mutations++;return new Response(JSON.stringify({data:q.includes('node(id:')?{node:{discussion:{id:'foreign'},replyTo:null}}:{repository:{discussion:{id:'correct',number:1,author:{login:'other'},viewerCanUpdate:true}}}}),{headers:{'Content-Type':'application/json'}});});try{assert.equal((await request(e,'/posts/1',{title:'New title',body:'changed'},voter,'PATCH')).status,403);assert.equal((await request(e,'/posts/1/comments',{body:'hello',replyToId:'foreign'})).status,400);assert.equal(mutations,0);}finally{restore();e.db.close();}});
test('post writes use the fixed repository and pass Markdown as GraphQL variables',async()=>{const e=setup();await connection(e,voter);let submitted;const restore=mockFetch(async(_url,init)=>{const b=JSON.parse(init.body);if(b.query.startsWith('mutation')){submitted=b;return new Response(JSON.stringify({data:{createDiscussion:{discussion:{number:8}}}}));}return new Response(JSON.stringify({data:{repository:{discussionCategories:{nodes:[{id:'general',slug:'general'},{id:'announcements',slug:'announcements'}]}}}}));});try{assert.equal((await request(e,'/posts',{title:'Announcement',body:'hello',categoryId:'announcements'})).status,403);const body='## Marth\n\n![Hero](https://example.com/hero.png)\n" } mutation { bad }';const r=await request(e,'/posts',{title:'Rerun prediction',body,categoryId:'general',repositoryId:'attacker'});assert.equal(r.status,200);assert.equal(submitted.variables.input.repositoryId,'R_kgDOU5Auog');assert.equal(submitted.variables.input.body,body);assert.ok(!submitted.query.includes('example.com'));}finally{restore();e.db.close();}});

test('public uploaded images return exact binary bytes from D1 JSON blob representation',async()=>{const e=setup(),id='11111111-1111-4111-8111-111111111111',bytes=new Uint8Array([82,73,70,70,12,0,0,0,87,69,66,80,255,0,128]);e.db.prepare('INSERT INTO community_images VALUES(?,?,?,?,?,?)').run(id,'123','image/webp',bytes,bytes.length,new Date().toISOString());try{const r=await request(e,'/images/'+id,undefined,null);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/webp');assert.deepEqual(new Uint8Array(await r.arrayBuffer()),bytes);assert.equal((await request(e,'/images/22222222-2222-4222-8222-222222222222',undefined,null)).status,404);}finally{e.db.close();}});
