import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handle,hash} from './worker.mjs';
test('Website sessions control staff access and GitHub-linked registered voting',async()=>{
 const f=await fixture();f.env.SUPABASE_URL='https://website.test';f.env.SUPABASE_PUBLISHABLE_KEY='public-test';
 let valid=true,role='Manager',linked=false;const original=globalThis.fetch;
 globalThis.fetch=async(input,init)=>{assert.equal(init.headers.Authorization,'Bearer aaa.bbb.ccc');return new Response(JSON.stringify(String(input).endsWith('/user')?(valid?{id:'registered-user',identities:linked?[{provider:'github',identity_data:{sub:'3',user_name:'voter'}}]:[]}:{}):role),{status:valid?200:401,headers:{'Content-Type':'application/json'}});};
 const api=async(path,body)=>{const r=await handle(new Request('https://polls.test'+path,{method:body?'POST':'GET',headers:{Origin:'https://clustifle.github.io',Authorization:'Bearer aaa.bbb.ccc','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),f.env);return {status:r.status,data:await r.json()};};
 try{
  assert.equal((await api('/session')).data.user.role,'manager');
  const id=(await api('/polls',f.input)).data.id;
  assert.equal((await api('/polls/'+id+'/state',{status:'open',revision:1})).status,200);
  const choice=(await api('/polls/'+id)).data.poll.choices[0].id;
  assert.equal((await api('/polls/'+id+'/vote',{choice_id:choice})).status,403);
  role='User';linked=true;
  assert.equal((await api('/polls',f.input)).status,403);
  assert.equal((await api('/polls/'+id+'/vote',{choice_id:choice})).status,200);
  assert.equal(f.DB.sql.prepare('SELECT github_id FROM poll_votes').get().github_id,'3');
  valid=false;assert.equal((await api('/polls/'+id+'/vote',{choice_id:choice})).status,401);
  assert.equal((await f.api('/polls','owner',f.input)).status,403);
 }finally{globalThis.fetch=original;}
});
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));const wrap=(sql,args=[])=>({bind(...values){return wrap(sql,values);},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}});return {sql:db,prepare:wrap,async batch(queries){db.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};}
async function fixture(){const DB=database(),env={DB,SITE_URL:'https://clustifle.github.io/FEH-Rerun-Schedule-by-Clustifle/',HEAD_ADMIN_GITHUB_ID:'1',GITHUB_CLIENT_ID:'test',GITHUB_CLIENT_SECRET:'fixture-secret'},tokens={owner:'a'.repeat(64),manager:'b'.repeat(64),voter:'c'.repeat(64)};for(const [role,id] of [['owner','1'],['manager','2'],['voter','3']])DB.sql.prepare('INSERT INTO poll_sessions VALUES(?,?,?,?)').run(await hash(tokens[role]),id,role,Math.floor(Date.now()/1000)+3600);DB.sql.prepare('INSERT INTO poll_staff VALUES(?,?)').run('2','manager');async function api(path,role,body,method=body?'POST':'GET'){const r=await handle(new Request('https://polls.test'+path,{method,headers:{Origin:'https://clustifle.github.io',...(role?{Authorization:'Bearer '+tokens[role]}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,data:await r.json()};}const input={question:'Which revival do you prefer?',description:'Community feedback',choices:['NH Revival','HoF Revival'],featured:true,allow_change:true,results_mode:'after_vote',closes_at:null};return {DB,env,tokens,api,input};}
test('Draft privacy, staff access and publication lifecycle',async()=>{const f=await fixture();assert.equal((await f.api('/polls','voter',f.input)).status,403);const create=await f.api('/polls','manager',f.input);assert.equal(create.status,201);const id=create.data.id;assert.equal((await f.api('/polls/'+id)).status,404);assert.equal((await f.api('/polls?admin=1','voter')).status,403);assert.equal((await f.api('/polls')).data.polls.length,0);let p=(await f.api('/polls/'+id,'manager')).data.poll;assert.equal((await f.api('/polls/'+id+'/state','manager',{status:'open',revision:p.revision})).status,200);assert.equal((await f.api('/polls')).data.polls.length,1);p=(await f.api('/polls/'+id,'manager')).data.poll;assert.equal((await f.api('/polls/'+id,'manager',{...f.input,question:'Change after publication?',revision:p.revision},'PATCH')).status,400);assert.equal((await f.api('/polls/'+id+'/state','manager',{status:'closed',revision:p.revision})).status,200);p=(await f.api('/polls/'+id,'manager')).data.poll;assert.equal((await f.api('/polls/'+id+'/state','manager',{status:'archived',revision:p.revision})).status,200);assert.equal((await f.api('/polls')).data.polls.length,0);assert.equal(f.DB.sql.prepare('SELECT COUNT(*) AS n FROM poll_history').get().n,4);});
test('One vote per account, private results, change policy and closed voting',async()=>{const f=await fixture();const id=(await f.api('/polls','owner',f.input)).data.id;await f.api('/polls/'+id+'/state','owner',{status:'open',revision:1});let p=(await f.api('/polls/'+id)).data.poll;assert.equal(p.total,null);assert.equal(p.choices[0].votes,undefined);assert.equal((await f.api('/polls/'+id+'/vote',null,{choice_id:p.choices[0].id})).status,401);assert.equal((await f.api('/polls/'+id+'/vote','voter',{choice_id:'invalid'})).status,409);let vote=await f.api('/polls/'+id+'/vote','voter',{choice_id:p.choices[0].id});assert.equal(vote.status,200);assert.equal(vote.data.poll.total,1);vote=await f.api('/polls/'+id+'/vote','voter',{choice_id:p.choices[1].id});assert.equal(vote.data.poll.total,1);assert.equal(f.DB.sql.prepare('SELECT COUNT(*) AS n FROM poll_votes').get().n,1);assert.equal((await f.api('/polls/'+id)).data.poll.total,null);f.DB.sql.prepare('UPDATE polls SET allow_change=0 WHERE id=?').run(id);assert.equal((await f.api('/polls/'+id+'/vote','voter',{choice_id:p.choices[0].id})).status,409);await f.api('/polls/'+id+'/state','owner',{status:'closed',revision:2});assert.equal((await f.api('/polls/'+id+'/vote','voter',{choice_id:p.choices[0].id})).status,409);assert.equal((await f.api('/polls/'+id)).data.poll.total,1);});
test('Deadline, foreign choice, stale revisions and no voter identity disclosure',async()=>{const f=await fixture();const id=(await f.api('/polls','owner',f.input)).data.id,other=(await f.api('/polls','owner',f.input)).data.id;await f.api('/polls/'+id+'/state','owner',{status:'open',revision:1});const p=(await f.api('/polls/'+id,'owner')).data.poll,foreign=(await f.api('/polls/'+other,'owner')).data.poll.choices[0];assert.equal((await f.api('/polls/'+id+'/vote','voter',{choice_id:foreign.id})).status,409);assert.equal((await f.api('/polls/'+id,'owner',{...f.input,revision:1},'PATCH')).status,409);assert.ok(!JSON.stringify(p).includes('github_id'));f.DB.sql.prepare("UPDATE polls SET closes_at='2020-01-01T00:00:00.000Z' WHERE id=?").run(id);assert.equal((await f.api('/polls/'+id)).data.poll.status,'closed');assert.equal((await f.api('/polls/'+id+'/vote','voter',{choice_id:p.choices[0].id})).status,409);});
test('Staff revocation is immediate; Head Admin cannot be transferred; origins and expired sessions rejected',async()=>{const f=await fixture();assert.equal((await f.api('/staff','manager')).status,403);assert.equal((await f.api('/staff','owner',{github_id:'1',enabled:false})).status,400);assert.equal((await f.api('/staff','owner',{github_id:'2',enabled:false})).status,200);assert.equal((await f.api('/polls','manager',f.input)).status,403);assert.equal((await f.api('/history','voter')).status,403);const r=await handle(new Request('https://polls.test/polls',{headers:{Origin:'https://bad.example'}}),f.env);assert.equal(r.status,403);f.DB.sql.prepare('UPDATE poll_sessions SET expires_at=0 WHERE github_id=?').run('1');assert.equal((await f.api('/polls','owner',f.input)).status,403);});
test('GitHub OAuth uses state, browser binding and PKCE; callback without browser cookie fails',async()=>{const f=await fixture();const login=await handle(new Request('https://polls.test/auth/github?nonce='+'d'.repeat(64)),f.env);assert.equal(login.status,302);const url=new URL(login.headers.get('Location'));assert.equal(url.hostname,'github.com');assert.equal(url.searchParams.get('scope'),null);assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.match(login.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);const callback=await handle(new Request('https://polls.test/auth/callback?code=fake&state='+url.searchParams.get('state')),f.env);assert.equal(callback.status,400);assert.equal(f.DB.sql.prepare('SELECT COUNT(*) AS n FROM poll_oauth').get().n,1);});
