import {useEffect,useState} from 'react';
import {assetUrl,supabase} from './static-data';
import {goTo,viewUrl} from './routes';
import packageInfo from '../package.json';
import InstallApp from './InstallApp';
type ManagerCredit={username:string;display_name:string};
export default function About(){
 const [managers,setManagers]=useState<ManagerCredit[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;supabase.rpc('public_schedule_manager_credits').then(({data,error})=>{if(!active)return;setFailed(!!error);setManagers(error?[]:(data||[]) as ManagerCredit[]);setLoading(false);});return()=>{active=false;};},[]);
 const build=document.querySelector('meta[name="deployment-id"]')?.getAttribute('content');const date=build?new Date(build):null;
 return <section id="settings-About" className="settings-group settings-about"><div className="about-brand"><img className="settings-about-logo" src={assetUrl('clustifle-feh-rerun-logo.png')} alt="Fire Emblem Heroes Rerun Schedule by Clustifle"/><h3>About FEH Rerun</h3><p>An unofficial Fire Emblem Heroes schedule and rerun tracker.</p><span className="about-version">Version {packageInfo.version}{date&&!Number.isNaN(date.getTime())&&<> · Build {date.toLocaleDateString()}</>}</span></div><div className="about-info-grid"><section className="about-info-card"><h4>Creator</h4><strong>Clustifle</strong><p>Website design, development, and schedule management.</p><nav className="settings-about-links" aria-label="Clustifle social links"><a href="https://www.youtube.com/@Clustifle" target="_blank" rel="noopener noreferrer">YouTube ↗</a><a href="https://x.com/Clustifle" target="_blank" rel="noopener noreferrer">X ↗</a><a href="https://github.com/clustifle/FEH-Rerun-Schedule-by-Clustifle" target="_blank" rel="noopener noreferrer">GitHub ↗</a></nav></section><section className="about-info-card"><h4>Current Schedule Managers</h4>{loading?<p role="status">Loading public profiles…</p>:failed?<p>Schedule Manager information is temporarily unavailable.</p>:managers.length?<ul className="about-manager-list">{managers.map(manager=><li key={manager.username}><a href={viewUrl('Profile','',manager.username)} onClick={e=>{if(e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();goTo(viewUrl('Profile','',manager.username));}}}>{manager.display_name||manager.username}<small>@{manager.username}</small></a></li>)}</ul>:<p>No public Schedule Manager profiles listed.</p>}</section><section className="about-info-card"><h4>Credits & special thanks</h4><p><a href="https://www.reddit.com/user/King41bert0713/" target="_blank" rel="noopener noreferrer">u/King41bert0713</a> — feature ideas and feedback.</p><p>Game UI and realm backgrounds from the <a href="https://feheroes.fandom.com/wiki/Game_assets_collection#UI_Sprite_sheets" target="_blank" rel="noopener noreferrer">FEH Wiki UI Sprite sheets</a> and combat-background collection. Font and original wallpaper supplied by Clustifle.</p><p>Originally created on ChatGPT Sites; hosted on GitHub Pages.</p></section><section className="about-info-card"><h4>Copyright</h4><p>Fire Emblem Heroes and game artwork © Nintendo / INTELLIGENT SYSTEMS.</p><p>This is an unofficial fan project, unaffiliated with Nintendo or INTELLIGENT SYSTEMS.</p><InstallApp/></section></div></section>;
}
