import {useEffect,useRef,useState,type FormEvent} from 'react';
import {supabase} from './static-data';
import './AccountSetup.css';
export default function AccountSetup(){
 const dialog=useRef<HTMLDialogElement>(null),sequence=useRef(0);
 const [id,setId]=useState(''),[needed,setNeeded]=useState(false),[checking,setChecking]=useState(false),[username,setUsername]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(false);
 useEffect(()=>{let alive=true;async function check(){const ticket=++sequence.current;try{const {data:{session},error}=await supabase.auth.getSession();if(!alive||ticket!==sequence.current)return;if(error)throw error;if(!session){setNeeded(false);setId('');return;}setId(session.user.id);setChecking(true);const {data,error:profileError}=await supabase.from('tracker_profiles').select('username,display_name').eq('id',session.user.id).maybeSingle();if(!alive||ticket!==sequence.current)return;if(profileError)throw profileError;setName(data?.display_name||'');setUsername(data?.username||'');setError('');setRetry(false);setNeeded(!/^[a-z0-9_]{3,24}$/.test(data?.username||''));}catch{if(alive&&ticket===sequence.current){setError('Could not check your username. Please try again.');setRetry(true);setNeeded(true);}}finally{if(alive&&ticket===sequence.current)setChecking(false);}}void check();window.addEventListener('owner-session-change',check);window.addEventListener('profile-updated',check);return()=>{alive=false;sequence.current++;window.removeEventListener('owner-session-change',check);window.removeEventListener('profile-updated',check);};},[]);
 useEffect(()=>{if(needed&&!dialog.current?.open)dialog.current?.showModal();else if(!needed)dialog.current?.close();},[needed]);
 async function save(e:FormEvent){e.preventDefault();if(busy||checking||retry||!id)return;const value=username.trim();if(!/^[a-z0-9_]{3,24}$/.test(value)){setError('Use 3–24 lowercase letters, numbers or underscores.');return;}setBusy(true);setError('');try{const {error}=await supabase.from('tracker_profiles').upsert({id,username:value,display_name:name.trim()||value},{onConflict:'id'});if(error)throw error;setNeeded(false);window.dispatchEvent(new Event('profile-updated'));}catch(e){setError(e&&typeof e==='object'&&'code' in e&&e.code==='23505'?'That username is already taken. Choose another.':'Could not save your username. Please try again.');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="account-username-setup" aria-labelledby="username-setup-title" onCancel={e=>e.preventDefault()}><form onSubmit={save}><h2 id="username-setup-title">Set your username</h2>{checking?<p role="status">Checking your account...</p>:retry?<><p role="alert">{error}</p><button type="button" onClick={()=>window.dispatchEvent(new Event('owner-session-change'))}>Try again</button></>:<><p>Choose a username to continue to the schedules. You can customize your profile later.</p><label>Username<input autoFocus required autoComplete="username" minLength={3} maxLength={24} pattern="[a-z0-9_]{3,24}" value={username} disabled={busy} onChange={e=>{setUsername(e.target.value.toLowerCase());setError('');}}/></label><small>3–24 lowercase letters, numbers or underscores.</small>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving...':'Save & continue'}</button></>}</form></dialog>;
}

