import {useEffect,useState} from 'react';
import {Shield,CalendarDays,ClipboardCheck,Plus,X} from 'lucide-react';
import {UpcomingEvents} from './ModsTool';
import type {BetaHero} from './V2Workspace';
export default function AdministrativeDashboard({heroes,userId,owner,loading,onNavigate,onAdd,onEdit}:{heroes:BetaHero[];userId:string;owner:boolean;loading:boolean;onNavigate:(s:string)=>void;onAdd:()=>void;onEdit:(id:string)=>void}){
 const key='fehrs-admin-quickstart-seen:'+userId;
 const [quickStart,setQuickStart]=useState(()=>{try{return localStorage.getItem(key)!=='1';}catch{return true;}});
 useEffect(()=>{try{localStorage.setItem(key,'1');}catch{}},[key]);
 const issues=heroes.filter(h=>!h.portrait||!h.weapon_type||!h.move_type),scheduled=heroes.filter(h=>h.month).length;
 const metrics=[{key:'heroes',label:'Total heroes',count:heroes.length,detail:'Browse and edit hero records',Icon:Shield},{key:'schedules',label:'Rerun month recorded',count:scheduled,detail:'Heroes with an assigned rerun month',Icon:CalendarDays},{key:'mods-edit',label:'Records to check',count:issues.length,detail:'Missing portrait, weapon, or movement',Icon:ClipboardCheck}];
 return <div className="adm-dashboard"><header className="adm-overview-header"><div><h3>Overview</h3><p>Hero records, upcoming events, and work that needs attention.</p></div><button onClick={()=>setQuickStart(true)}>Quick Start</button></header>{quickStart&&<section className="adm-quick-start" aria-label="Quick Start"><div className="adm-quick-label">QUICK START</div><div><header><h3>Get started</h3><button aria-label="Dismiss Quick Start" onClick={()=>setQuickStart(false)}><X size={18}/></button></header><p>Choose a workspace to begin. This guide appears automatically once on this browser.</p>{[['heroes','Review hero records'],['waitlists','Arrange waitlists and consideration'],['mods-edit','Bulk edit heroes and manage FEH versions']].map(([section,text],i)=><button key={section} onClick={()=>onNavigate(section)}><span>{i+1}</span>{text}</button>)}</div></section>}<div className="adm-overview-actions"><button className="primary" onClick={onAdd}><Plus size={16}/>Add hero</button><button onClick={()=>onNavigate('schedules')}>Manage schedules</button><button onClick={()=>onNavigate('waitlists')}>Manage waitlists</button></div><div className="adm-dashboard-tiles">{metrics.map(({key,label,count,detail,Icon})=><button className="adm-tile" key={key} onClick={()=>onNavigate(key)}><header><Icon size={22}/><h3>{label}</h3><strong>{loading&&!heroes.length?'…':count}</strong></header><span>{detail}</span></button>)}</div><div className="adm-overview-columns"><section className="adm-overview-panel"><header><h3>Records to check</h3><button onClick={()=>onNavigate('mods-edit')}>Open Mods Edit</button></header><p>Complete these missing details to improve the hero catalog.</p>{loading&&!heroes.length?<p role="status">Loading records…</p>:issues.length?<ul className="adm-attention-list">{issues.slice(0,10).map(h=><li key={h.id}><div><strong>{h.name}</strong><small>{h.title}</small><span>{[!h.portrait?'Portrait':'',!h.weapon_type?'Weapon type':'',!h.move_type?'Movement type':''].filter(Boolean).join(' · ')}</span></div><button onClick={()=>onEdit(h.id)} aria-label={'Edit '+h.name}>Edit</button></li>)}</ul>:<p>All hero records have portrait, weapon, and movement details.</p>}{issues.length>10&&<p>{issues.length-10} more records need attention. Use Mods Edit to review them.</p>}</section><section className="adm-overview-panel mods-tool adm-tool-pane"><UpcomingEvents owner={owner} onContent={()=>onNavigate('content')}/></section></div></div>;
}
