import {useDefinitions,definitionNames} from './catalog';
import HeroPortraitMarks from './HeroPortraitMarks';
import AdvancedFilters from './AdvancedFilters';
import {useMemo,useState,useRef,useEffect} from 'react';
import {Grid2X2,List,Plus,Search,Shield,LayoutGrid,Table2,X,RotateCcw} from 'lucide-react';
import {portraitUrl} from './static-data';
import {normalizePool} from './hero-pools';
import './AllHeroes.css';
type Hero={id:string;name:string;title:string;category:string;heroic_grail?:boolean;demote?:boolean;pool?:string|null;schedule?:string;month?:string|null;updated?:string;blessing?:string|null;color:string;portrait:string|null;weapon_type?:string|null;move_type?:string|null;searchText?:string;notes?:string};
const collator=new Intl.Collator('en',{sensitivity:'base',numeric:true});
const scheduleName=(s:string)=>({'Schedule Under Consideration':'Schedule Under Consideration','General':'General Schedule','Remix':'Remix Schedule','Monthly Revival':'L/M Revival','Forging Bonds Revival':'NH Revival','Hall of Forms Revival':'HoF Revival','Waitlist':'L/M/E Waitlist','DSH Waitlist':'DSH Waitlist','NHR Waitlist':'NHR Waitlist','Remix Waitlist':'Remix Waitlist'} as Record<string,string>)[s]||'Unscheduled';
const monthName=(month?:string|null)=>month&&/^\d{4}-\d{2}/.test(month)?new Intl.DateTimeFormat('en',{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(month.slice(0,7)+'-01T00:00:00Z')):'Not recorded';
const sortOptions=[['name-asc','Name · A–Z'],['name-desc','Name · Z–A'],['title','Hero title'],['type','Hero type'],['color','Weapon color'],['weapon','Weapon type'],['movement','Movement type'],['month-asc','Rerun · earliest'],['month-desc','Rerun · latest'],['updated','Recently updated']];
export default function AllHeroes<T extends Hero>({heroes,onView,canEdit,onAdd}:{heroes:T[];onView:(hero:T)=>void;canEdit:boolean;onAdd:()=>void}){
 const [sort,setSort]=useState('name-asc'),[view,setView]=useState('cards'),[search,setSearch]=useState('');
 const [type,setType]=useState('All heroes'),[color,setColor]=useState('All'),[weapon,setWeapon]=useState('All'),[move,setMove]=useState('All'),[pool,setPool]=useState('All'),[showGrails,setShowGrails]=useState(true),[schedule,setSchedule]=useState('All'),[blessing,setBlessing]=useState('All'),[demote,setDemote]=useState('All');
 const results=useRef<HTMLDivElement>(null);
 const definitions=useDefinitions();
 const categories=definitionNames(definitions,'hero_type',heroes.map(h=>h.category));
 const schedules=useMemo(()=>Array.from(new Set(heroes.map(h=>h.schedule||'None'))).sort((a,b)=>collator.compare(scheduleName(a),scheduleName(b))),[heroes]);
 const blessings=useMemo(()=>Array.from(new Set(heroes.map(h=>h.blessing).filter((s):s is string=>Boolean(s)))).sort(collator.compare),[heroes]);
 const query=search.trim().toLocaleLowerCase();
 const rows=useMemo(()=>heroes.filter(h=>{
 const text=(h.name+' '+h.title+' '+h.category+' '+(h.notes||'')).toLocaleLowerCase();
 return query.split(/\s+/).every(word=>text.includes(word))&&(type==='All heroes'||h.category===type)&&(color==='All'||h.color===color)&&(pool==='All'||normalizePool(h.pool,h.category)===pool)&&(showGrails||!h.heroic_grail)&&(weapon==='All'||(weapon==='Unassigned'?!h.weapon_type:h.weapon_type===weapon))&&(move==='All'||(move==='Unassigned'?!h.move_type:h.move_type===move))&&(schedule==='All'||(h.schedule||'None')===schedule)&&(blessing==='All'||(blessing==='Unassigned'?!h.blessing:h.blessing===blessing))&&(demote==='All'||Boolean(h.demote)===(demote==='Yes'));
 }).sort((a,b)=>{
 const names=collator.compare(a.name,b.name)||collator.compare(a.title,b.title)||a.id.localeCompare(b.id);
 if(sort==='name-desc')return -names;
 if(sort.startsWith('month-')){const am=a.schedule==='None'?null:a.month,bm=b.schedule==='None'?null:b.month;if(!am||!bm)return am?-1:bm?1:names;return (sort==='month-desc'?-1:1)*collator.compare(am,bm)||names;}
 if(sort==='updated')return collator.compare(b.updated||'',a.updated||'')||names;
 if(sort==='color')return ['Red','Blue','Green','Colorless'].indexOf(a.color)-['Red','Blue','Green','Colorless'].indexOf(b.color)||names;
 const field=({title:'title',type:'category',weapon:'weapon_type',movement:'move_type'} as const)[sort as 'title'|'type'|'weapon'|'movement'];
 return field?collator.compare(a[field]||'',b[field]||'')||names:names;
 }),[heroes,query,type,color,pool,showGrails,weapon,move,schedule,blessing,demote,sort]);
 useEffect(()=>{if(results.current)results.current.scrollTop=0;},[query,type,color,pool,showGrails,weapon,move,schedule,blessing,demote,sort,view]);
 function reset(){setSearch('');setType('All heroes');setColor('All');setWeapon('All');setMove('All');setPool('All');setShowGrails(true);setSchedule('All');setBlessing('All');setDemote('All');}
 const chips:[string,()=>void][]=[];
 if(query)chips.push(['Search: '+search,()=>setSearch('')]);if(type!=='All heroes')chips.push([type,()=>setType('All heroes')]);if(color!=='All')chips.push([color,()=>setColor('All')]);if(weapon!=='All')chips.push(['Weapon: '+weapon,()=>setWeapon('All')]);if(move!=='All')chips.push(['Movement: '+move,()=>setMove('All')]);if(pool!=='All')chips.push([pool,()=>setPool('All')]);if(!showGrails)chips.push(['Grails hidden',()=>setShowGrails(true)]);if(schedule!=='All')chips.push([scheduleName(schedule),()=>setSchedule('All')]);if(blessing!=='All')chips.push(['Blessing: '+blessing,()=>setBlessing('All')]);if(demote!=='All')chips.push([demote==='Yes'?'Demotes only':'Demotes hidden',()=>setDemote('All')]);
 const portrait=(h:T)=><span className="all-heroes-portrait">{h.portrait?<img src={portraitUrl(h.portrait)} alt="" loading="lazy" decoding="async"/>:<Shield size={28}/>}<HeroPortraitMarks hero={h}/></span>;
 const extra=(label:string,value:string,change:(s:string)=>void,options:[string,string][])=><section className="filter-section"><h3>{label}</h3><select aria-label={label} value={value} onChange={e=>change(e.target.value)}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></section>;
 return <section className="all-heroes" aria-label="All Heroes directory">
 <div className="all-heroes-tools"><label className="all-heroes-search"><Search size={19}/><input type="search" aria-label="Search all heroes" placeholder="Search name, title, type or notes…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="directory-filter-control"><AdvancedFilters {...{showGrails,move,weapon,categories,type,color,pool,search}} matches={rows.length} onShowGrails={setShowGrails} onMove={setMove} onWeapon={setWeapon} onType={setType} onColor={setColor} onPool={setPool} onSearch={setSearch} onReset={reset} extraActive={Number(schedule!=='All')+Number(blessing!=='All')+Number(demote!=='All')}>{extra('Schedule',schedule,setSchedule,[['All','Any schedule'],...schedules.map(s=>[s,scheduleName(s)] as [string,string])])}{extra('Blessing',blessing,setBlessing,[['All','Any blessing'],['Unassigned','Not assigned'],...blessings.map(s=>[s,s] as [string,string])])}{extra('Demote status',demote,setDemote,[['All','All heroes'],['Yes','Demotes only'],['No','Hide demotes']])}</AdvancedFilters></div>{canEdit&&<button className="secondary directory-add" aria-label="Add hero" title="Add hero" onClick={onAdd}><Plus size={18}/></button>}</div>
 <div className="directory-display-tools"><label className="all-heroes-sort">Sort<select aria-label="Sort heroes" value={sort} onChange={e=>setSort(e.target.value)}>{sortOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="all-heroes-views" role="group" aria-label="Hero directory view">{([['cards','Cards',Grid2X2],['compact','Compact',LayoutGrid],['list','List',List],['table','Table',Table2]] as const).map(([key,label,Icon])=><button key={key} className="directory-view" aria-label={label+' view'} title={label+' view'} aria-pressed={view===key} onClick={()=>setView(key)}><Icon size={19}/></button>)}</div><p className="all-heroes-count" role="status">{rows.length} of {heroes.length} heroes</p></div>
 {chips.length>0&&<div className="directory-filter-chips" aria-label="Active filters">{chips.map(([label,clear])=><button key={label} onClick={clear} aria-label={'Remove filter '+label}>{label}<X size={14}/></button>)}<button onClick={reset}><RotateCcw size={14}/>Clear all</button></div>}
 <div ref={results} className={'all-heroes-results '+view+'-view'} tabIndex={0} aria-label="Hero results; scroll to browse">
 {view==='table'&&rows.length>0?<table className="directory-table"><thead><tr><th>Hero</th><th>Type / pool</th><th>Weapon / movement</th><th>Schedule</th><th>Rerun month</th></tr></thead><tbody>{rows.map(h=><tr key={h.id}><td><button className="directory-table-hero" onClick={()=>onView(h)}>{portrait(h)}<span><strong>{h.name}</strong><span>{h.title||'Untitled hero'}</span></span></button></td><td>{h.category}<small>{normalizePool(h.pool,h.category)}{h.heroic_grail?' · Heroic Grails':''}</small></td><td>{h.color} {h.weapon_type||'weapon unassigned'}<small>{h.move_type||'Movement unassigned'}</small></td><td>{scheduleName(h.schedule||'None')}</td><td>{monthName(h.schedule==='None'?null:h.month)}</td></tr>)}</tbody></table>:rows.map(h=><button key={h.id} className={'all-heroes-card '+h.color.toLowerCase()} onClick={()=>onView(h)} aria-label={'View '+h.name+' · '+h.title}>{portrait(h)}<span className="all-heroes-copy"><strong>{h.name}</strong><span>{h.title||'Untitled hero'}</span>{view!=='compact'&&<span className="directory-hero-type">{h.category==='Chosen Hero'?'Chosen':h.category}{h.heroic_grail?' · Heroic Grails':''}</span>}</span>{view!=='compact'&&<span className="directory-rerun"><span>{scheduleName(h.schedule||'None')}</span><strong>{monthName(h.schedule==='None'?null:h.month)}</strong></span>}</button>)}
 {!rows.length&&<div className="all-heroes-empty"><Shield size={30}/><h3>{heroes.length?'No matching heroes':'No heroes yet'}</h3><p>{heroes.length?'Try another search or clear your filters.':'Heroes will appear here when they are added.'}</p>{chips.length>0&&<button className="secondary" onClick={reset}>Clear filters</button>}</div>}</div></section>;
}
