import {useMemo,useState} from 'react';
import {Grid2X2,List,Plus,Search,Shield} from 'lucide-react';
import {portraitUrl,assetUrl} from './static-data';
type Hero={id:string;name:string;title:string;category:string;color:string;portrait:string|null;weapon_type?:string|null;move_type?:string|null};
export default function AllHeroes<T extends Hero>({heroes,onView,canEdit,onAdd}:{heroes:T[];onView:(hero:T)=>void;canEdit:boolean;onAdd:()=>void}){
 const [sort,setSort]=useState('asc'),[view,setView]=useState('grid'),[search,setSearch]=useState('');
 const rows=useMemo(()=>heroes.filter(h=>(h.name+' '+h.title).toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>{const result=a.name.localeCompare(b.name,'en',{sensitivity:'base',numeric:true})||a.title.localeCompare(b.title,'en',{sensitivity:'base'})||a.id.localeCompare(b.id);return sort==='asc'?result:-result;}),[heroes,search,sort]);
 return <section className="all-heroes" aria-label="All Heroes directory"><div className="all-heroes-tools"><label className="all-heroes-search"><Search size={18}/><input type="search" aria-label="Search all heroes" placeholder="Find a hero…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="all-heroes-sort">Sort by name<select aria-label="Sort heroes by name" value={sort} onChange={e=>setSort(e.target.value)}><option value="asc">A to Z</option><option value="desc">Z to A</option></select></label><div className="all-heroes-views" role="group" aria-label="Hero directory view"><button className="toolbar-icon" aria-label="List view" title="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={21}/></button><button className="toolbar-icon" aria-label="Grid view" title="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><Grid2X2 size={21}/></button></div>{canEdit&&<button className="toolbar-icon" aria-label="Add" title="Add a hero" onClick={onAdd}><Plus size={21}/></button>}</div><p className="all-heroes-count" role="status">{rows.length} {rows.length===1?'hero':'heroes'}</p><div className={'all-heroes-results '+view+'-view'}>{rows.map(h=><button key={h.id} className={'all-heroes-card '+h.color.toLowerCase()} onClick={()=>onView(h)} aria-label={'View '+h.name+' · '+h.title}><span className="all-heroes-portrait">{h.portrait?<img src={portraitUrl(h.portrait)} alt="" loading="lazy" decoding="async"/>:<Shield size={28}/>}</span><span className="all-heroes-copy"><strong>{h.name}</strong><span>{h.title||'Untitled hero'}</span><small>{h.category==='Chosen Hero'?'Chosen':h.category}</small></span><span className="all-heroes-attributes">{h.weapon_type&&<img src={assetUrl('weapon-types/'+h.color.toLowerCase()+'-'+h.weapon_type.toLowerCase()+'.webp')} alt={h.color+' '+h.weapon_type} title={h.color+' '+h.weapon_type}/>} {h.move_type&&<img src={assetUrl('move-types/'+h.move_type.toLowerCase()+'.webp')} alt={h.move_type} title={h.move_type}/>}</span></button>)}</div>{!rows.length&&<p className="all-heroes-empty">{heroes.length?'No heroes match your search.':'No heroes have been added yet.'}</p>}</section>;
}
