import {useRef,useState,type ClipboardEvent,type DragEvent} from 'react';
import {Bold,Italic,Heading2,List,ListOrdered,Quote,Code,Link,Image,Upload,Table,Eye,Pencil,Smile,CheckSquare} from 'lucide-react';
import CommunityMarkdown from './CommunityMarkdown';
import {uploadCommunityImage} from './community-api';
export default function CommunityEditor({value,onChange,disabled=false,label='Post content'}:{value:string;onChange:(s:string)=>void;disabled?:boolean;label?:string}){
 const text=useRef<HTMLTextAreaElement>(null),file=useRef<HTMLInputElement>(null),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[insert,setInsert]=useState<'image'|'link'|null>(null),[url,setUrl]=useState(''),[description,setDescription]=useState('');
 function wrap(before:string,after='',placeholder='text'){const el=text.current,start=el?.selectionStart??value.length,end=el?.selectionEnd??start,selected=value.slice(start,end)||placeholder;onChange(value.slice(0,start)+before+selected+after+value.slice(end));setPreview(false);requestAnimationFrame(()=>{text.current?.focus();text.current?.setSelectionRange(start+before.length,start+before.length+selected.length);});}
 async function upload(image:File){if(disabled||busy)return;setBusy(true);setError('');try{const src=await uploadCommunityImage(image);wrap('\n![',']('+src+')\n',image.name.replace(/[\[\]\r\n]/g,' ').slice(0,80)||'Picture');}catch(e){setError(e instanceof Error?e.message:'Could not upload the picture.');}finally{setBusy(false);if(file.current)file.current.value='';}}
 function paste(e:ClipboardEvent){const image=Array.from(e.clipboardData.files).find(f=>f.type.startsWith('image/'));if(image){e.preventDefault();void upload(image);}}
 function drop(e:DragEvent){if(!e.dataTransfer.files.length)return;e.preventDefault();const image=e.dataTransfer.files[0];void upload(image);}
 const tools=[['Bold',Bold,()=>wrap('**','**')],['Italic',Italic,()=>wrap('*','*')],['Heading',Heading2,()=>wrap('\n## ','\n','Heading')],['Bullet list',List,()=>wrap('\n- ','\n','Item')],['Numbered list',ListOrdered,()=>wrap('\n1. ','\n','Item')],['Task list',CheckSquare,()=>wrap('\n- [ ] ','\n','Task')],['Quote',Quote,()=>wrap('\n> ','\n','Quote')],['Code block',Code,()=>wrap('\n```\n','\n```\n','code')],['Table',Table,()=>wrap('\n','\n','| Hero | Rerun |\n| --- | --- |\n| Marth | To be confirmed |')],['Insert link',Link,()=>{setInsert('link');setUrl('');setDescription('');}],['Insert image URL',Image,()=>{setInsert('image');setUrl('');setDescription('');}],['Upload picture',Upload,()=>file.current?.click()],['Emoji',Smile,()=>wrap('','','✨')]] as const;
 return <div className="community-editor" onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={drop}>
  <div className="community-editor-tools" role="toolbar" aria-label="Text formatting">{tools.map(([name,Icon,action])=><button key={name} type="button" className="icon-button" title={name} aria-label={name} disabled={disabled||busy} onClick={action}><Icon size={17}/></button>)}<button type="button" className="secondary community-preview-switch" aria-pressed={preview} onClick={()=>setPreview(!preview)}>{preview?<Pencil size={16}/>:<Eye size={16}/>} {preview?'Write':'Preview'}</button></div>
  <input ref={file} type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/>
  {insert&&<div className="community-insert"><label>{insert==='image'?'Image URL':'Link URL'}<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>{insert==='image'?'Picture description':'Link text'}<input maxLength={200} value={description} onChange={e=>setDescription(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>setInsert(null)}>Cancel</button><button type="button" className="primary" onClick={()=>{try{const valid=new URL(url);if(valid.protocol!=='https:')throw Error();wrap((insert==='image'?'!':'')+'[',']('+valid.href.replaceAll('(','%28').replaceAll(')','%29')+')',description.replace(/[\[\]\r\n]/g,' ')||'Picture');setInsert(null);setError('');}catch{setError('Enter a complete HTTPS URL.');}}}>Insert</button></div>}
  {preview?<div className="community-editor-preview" aria-label="Content preview">{value.trim()?<CommunityMarkdown body={value}/>:<p>Your preview will appear here.</p>}</div>:<label className="community-editor-input">{label}<textarea ref={text} aria-label={label} rows={9} maxLength={20000} value={value} disabled={disabled||busy} onChange={e=>onChange(e.target.value)} onPaste={paste} placeholder="Share a thought, ask a question, or discuss a rerun…"/></label>}
  <small>Markdown supported · paste or drop a picture · {value.length.toLocaleString()} / 20,000</small>{busy&&<p role="status">Optimizing and uploading picture…</p>}{error&&<p role="alert" className="error">{error}</p>}
 </div>;
}
