import {useEffect,useRef,useState} from 'react';
import {useEditor,EditorContent} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import ImageExtension from '@tiptap/extension-image';
import {Table as TableExtension,TableRow,TableHeader,TableCell} from '@tiptap/extension-table';
import Placeholder from '@tiptap/extension-placeholder';
import Turndown from 'turndown';
import {Bold,Italic,Strikethrough,Heading2,List,ListOrdered,Quote,Code,Link,Image,Upload,Table,Undo2,Redo2,Smile} from 'lucide-react';
import {renderCommunityMarkdown} from './CommunityMarkdown';
import {uploadCommunityImage} from './community-api';
const converter=new Turndown({headingStyle:'atx',codeBlockStyle:'fenced',bulletListMarker:'-'});
converter.addRule('tables',{filter:'table',replacement:(_text,node)=>'\n\n'+(node as HTMLElement).outerHTML+'\n\n'});
export default function CommunityEditor({value,onChange,disabled=false,label='Post content'}:{value:string;onChange:(s:string)=>void;disabled?:boolean;label?:string}){
 const file=useRef<HTMLInputElement>(null),last=useRef(value),change=useRef(onChange),[busy,setBusy]=useState(false),[error,setError]=useState(''),[insert,setInsert]=useState<'image'|'link'|null>(null),[url,setUrl]=useState(''),[description,setDescription]=useState('');change.current=onChange;
 const editor=useEditor({extensions:[StarterKit,ImageExtension.configure({allowBase64:false}),TableExtension.configure({resizable:false}),TableRow,TableHeader,TableCell,Placeholder.configure({placeholder:'Share a thought, ask a question, or discuss a rerun…'})],content:renderCommunityMarkdown(value),editable:!disabled,editorProps:{attributes:{role:'textbox','aria-label':label,'aria-multiline':'true',class:'community-markdown community-visual-input'}},onUpdate:({editor})=>{const body=converter.turndown(editor.getHTML());last.current=body;change.current(body);}});
 useEffect(()=>{if(editor&&value!==last.current){last.current=value;editor.commands.setContent(renderCommunityMarkdown(value),{emitUpdate:false});}},[editor,value]);
 useEffect(()=>{editor?.setEditable(!disabled&&!busy);},[editor,disabled,busy]);
 async function upload(image:File){if(disabled||busy||!editor)return;setBusy(true);setError('');try{const src=await uploadCommunityImage(image);editor.chain().focus().setImage({src,alt:image.name.slice(0,80)}).run();}catch(e){setError(e instanceof Error?e.message:'Could not upload the picture.');}finally{setBusy(false);if(file.current)file.current.value='';}}
 const tools=[['Bold',Bold,()=>editor?.chain().focus().toggleBold().run(),'bold'],['Italic',Italic,()=>editor?.chain().focus().toggleItalic().run(),'italic'],['Strikethrough',Strikethrough,()=>editor?.chain().focus().toggleStrike().run(),'strike'],['Heading',Heading2,()=>editor?.chain().focus().toggleHeading({level:2}).run(),'heading'],['Bullet list',List,()=>editor?.chain().focus().toggleBulletList().run(),'bulletList'],['Numbered list',ListOrdered,()=>editor?.chain().focus().toggleOrderedList().run(),'orderedList'],['Quote',Quote,()=>editor?.chain().focus().toggleBlockquote().run(),'blockquote'],['Code block',Code,()=>editor?.chain().focus().toggleCodeBlock().run(),'codeBlock'],['Table',Table,()=>editor?.chain().focus().insertTable({rows:3,cols:2,withHeaderRow:true}).run(),'table'],['Insert link',Link,()=>{setInsert('link');setUrl('');setDescription('');},'link'],['Insert image URL',Image,()=>{setInsert('image');setUrl('');setDescription('');},'image'],['Upload picture',Upload,()=>file.current?.click(),''],['Emoji',Smile,()=>editor?.chain().focus().insertContent('✨').run(),''],['Undo',Undo2,()=>editor?.chain().focus().undo().run(),''],['Redo',Redo2,()=>editor?.chain().focus().redo().run(),'']] as const;
 return <div className="community-editor" onPaste={e=>{const image=Array.from(e.clipboardData.files).find(f=>f.type.startsWith('image/'));if(image){e.preventDefault();void upload(image);}}} onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={e=>{if(e.dataTransfer.files.length){e.preventDefault();void upload(e.dataTransfer.files[0]);}}}>
 <div className="community-editor-tools" role="toolbar" aria-label="Text formatting">{tools.map(([name,Icon,action,active])=><button key={name} type="button" className="icon-button" title={name} aria-label={name} aria-pressed={active?editor?.isActive(active):undefined} disabled={disabled||busy||!editor} onMouseDown={e=>e.preventDefault()} onClick={action}><Icon size={17}/></button>)}</div>
 <input ref={file} type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/>
 {insert&&<div className="community-insert"><label>{insert==='image'?'Image URL':'Link URL'}<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>{insert==='image'?'Picture description':'Link text'}<input maxLength={200} value={description} onChange={e=>setDescription(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>setInsert(null)}>Cancel</button><button type="button" className="primary" onClick={()=>{try{const valid=new URL(url);if(valid.protocol!=='https:')throw Error();if(insert==='image')editor?.chain().focus().setImage({src:valid.href,alt:description}).run();else if(description)editor?.chain().focus().insertContent({type:'text',text:description,marks:[{type:'link',attrs:{href:valid.href}}]}).run();else editor?.chain().focus().setLink({href:valid.href}).run();setInsert(null);setError('');}catch{setError('Enter a complete HTTPS URL.');}}}>Insert</button></div>}
 <span>{label}</span><EditorContent editor={editor}/><small>Visual editor · paste or drop a picture · {value.length.toLocaleString()} / 20,000</small>{value.length>20000&&<p role="alert" className="error">Shorten your content to 20,000 characters before publishing.</p>}{busy&&<p role="status">Optimizing and uploading picture…</p>}{error&&<p role="alert" className="error">{error}</p>}
 </div>;
}
