import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Plus,Search,RefreshCw,ArrowLeft,MessageSquare,ArrowUp,Bookmark,ExternalLink,ShieldCheck,Link,CheckCircle2} from 'lucide-react';
import {communityApi,discussionUrl,type CommunitySession,type Post,type Category,type PageInfo,type Comment} from './community-api';
import {supabase} from './static-data';
import {startGitHubAuth} from './github-auth';
import CommunityEditor from './CommunityEditor';
import CommunityMarkdown from './CommunityMarkdown';
import CommunityFlair,{flairs} from './CommunityFlair';
import './Community.css';
const errorText=(e:unknown)=>e instanceof Error?e.message:'Could not load Community.';
const date=(s:string)=>new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
function Author({author,dateValue}:{author:Post['author'];dateValue:string}){return <span className="community-author">{author&&<img src={author.avatarUrl} alt="" loading="lazy" width={24} height={24}/>}<span>{author?'@'+author.login:'Deleted account'} · {date(dateValue)}</span></span>;}
export default function Community({manage=false}:{manage?:boolean}){
 const [session,setSession]=useState<CommunitySession|null>(null),[categories,setCategories]=useState<Category[]>([]),[posts,setPosts]=useState<Post[]>([]),[pageInfo,setPageInfo]=useState<PageInfo>({hasNextPage:false}),[post,setPost]=useState<Post|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('updated'),[compose,setCompose]=useState(false),[editing,setEditing]=useState<Post|null>(null),[reply,setReply]=useState(''),[replyTo,setReplyTo]=useState<Comment|null>(null),[confirmClose,setConfirmClose]=useState(false),[bookmarks,setBookmarks]=useState<number[]>(()=>{try{return JSON.parse(localStorage.getItem('feh-community-bookmarks')||'[]');}catch{return [];}}),[savedOnly,setSavedOnly]=useState(false);
 const loadId=useRef(0),connected=!!session?.connected,user=session?.user,staff=user&&['owner','manager'].includes(user.role);
 const [editingReply,setEditingReply]=useState<Comment|null>(null);
 const [flairFilter,setFlairFilter]=useState('');
 async function account(){let r=await communityApi<CommunitySession>('/session');if(r.user&&!r.connected){const {data:{session:auth}}=await supabase.auth.getSession();if(auth?.provider_token){try{await communityApi('/connect',{token:auth.provider_token,publicReads:false});r=await communityApi<CommunitySession>('/session');}catch{}}}setSession(r);return r;}
 async function load(after?:string){const id=++loadId.current;setLoading(true);try{const params=new URLSearchParams({sort});if(search)params.set('q',search);if(category)params.set('category',category);if(flairFilter)params.set('flair',flairFilter);if(after)params.set('after',after);const r=await communityApi<{posts:Post[];pageInfo:PageInfo;setupRequired?:boolean}>('/posts?'+params);if(id!==loadId.current)return;setPosts(old=>after?[...old,...r.posts.filter(p=>!old.some(o=>o.number===p.number))]:r.posts);setPageInfo(r.pageInfo);setError('');}catch(e){if(id===loadId.current)setError(errorText(e));}finally{if(id===loadId.current)setLoading(false);}}
 async function open(number:number,updateUrl=true){setBusy(true);setError('');try{const r=await communityApi<{post:Post;setupRequired?:boolean}>('/posts/'+number);if(!r.post)throw Error('The community connection needs to be enabled before this post can be loaded.');setPost(r.post);setCompose(false);if(updateUrl)requestAnimationFrame(()=>document.querySelector('.community-workspace')?.scrollIntoView({behavior:'smooth',block:'start'}));setReply('');setReplyTo(null);if(updateUrl){const url=new URL(location.href);url.searchParams.set('post',String(number));history.pushState(null,'',url);}}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 useEffect(()=>{const timer=setTimeout(()=>setSearch(query.trim()),350);return()=>clearTimeout(timer);},[query]);
 useEffect(()=>{void load();},[search,category,sort,flairFilter]);
 useEffect(()=>{let alive=true;const refresh=()=>{void account().catch(e=>{if(alive)setError(errorText(e));});void communityApi<{categories:Category[]}>('/categories').then(r=>{if(alive)setCategories(r.categories);}).catch(e=>{if(alive)setError(errorText(e));});};refresh();const sync=()=>{const n=Number(new URLSearchParams(location.search).get('post'));if(Number.isSafeInteger(n)&&n>0)void open(n,false);else{setPost(null);setCompose(false);}};sync();window.addEventListener('owner-session-change',refresh);window.addEventListener('popstate',sync);return()=>{alive=false;window.removeEventListener('owner-session-change',refresh);window.removeEventListener('popstate',sync);};},[]);
 function back(){setPost(null);setCompose(false);setEditing(null);setReplyTo(null);const url=new URL(location.href);url.searchParams.delete('post');history.pushState(null,'',url);void load();}
 async function connect(publicReads=false){if(!user){window.dispatchEvent(new Event('open-owner-login'));return;}setBusy(true);try{await startGitHubAuth(user.website_id,{publicReads});}catch(e){setError(errorText(e));setBusy(false);}}
 async function action(path:string,body:unknown){setBusy(true);setError('');try{await communityApi(path,body);if(post)await open(post.number,false);setNotice('Community updated.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 function bookmark(n:number){setBookmarks(old=>{const next=old.includes(n)?old.filter(v=>v!==n):[...old,n];try{localStorage.setItem('feh-community-bookmarks',JSON.stringify(next));}catch{}return next;});}
 async function sendReply(e:FormEvent){e.preventDefault();if(!post)return;setBusy(true);setError('');try{await communityApi('/posts/'+post.number+'/comments',{body:reply,...(editingReply?{commentId:editingReply.id}:replyTo?{replyToId:replyTo.id}:{})},editingReply?'PATCH':'POST');setReply('');setReplyTo(null);setEditingReply(null);await open(post.number,false);setNotice('Your reply is published on GitHub Discussions.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function moreComments(){if(!post?.comments?.pageInfo.endCursor)return;setBusy(true);try{const r=await communityApi<{post:Post}>('/posts/'+post.number+'?after='+encodeURIComponent(post.comments.pageInfo.endCursor));setPost(old=>old?{...r.post,comments:{...r.post.comments!,nodes:[...old.comments!.nodes,...r.post.comments!.nodes]}}:r.post);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function threadReplies(c:Comment){if(!post)return;setBusy(true);try{const params=new URLSearchParams({commentId:c.id});if(c.replies?.pageInfo?.endCursor)params.set('after',c.replies.pageInfo.endCursor);const r=await communityApi<{replies:NonNullable<Comment['replies']>}>('/posts/'+post.number+'/replies?'+params);setPost(old=>old?.comments?{...old,comments:{...old.comments,nodes:old.comments.nodes.map(item=>item.id===c.id?{...item,replies:{...r.replies,nodes:[...(item.replies?.nodes||[]),...r.replies.nodes]}}:item)}}:old);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 function replyActions(c:Comment){return connected&&c.author?.login===user?.login?<div className="community-comment-actions">{c.viewerCanUpdate&&<button className="secondary" disabled={busy} onClick={()=>{setEditingReply(c);setReplyTo(null);setReply(c.body);document.getElementById('community-reply-form')?.scrollIntoView({behavior:'smooth',block:'center'});}}>Edit reply</button>}{c.viewerCanDelete&&<button className="secondary" disabled={busy} onClick={()=>{if(post&&window.confirm('Delete this reply from GitHub Discussions?'))void action('/posts/'+post.number+'/delete-comment',{commentId:c.id});}}>Delete reply</button>}</div>:null;}
 async function deletePost(){if(!post||!window.confirm('Delete this post and its replies from GitHub Discussions? This cannot be undone.'))return;setBusy(true);try{await communityApi('/posts/'+post.number+'/delete',{});back();setNotice('Post deleted.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 const shown=posts.filter(p=>!savedOnly||bookmarks.includes(p.number));
 return <section className={'community-workspace'+(manage?' community-management':'')}>
  <div className="community-intro"><div><h3>{manage?'Community management':'Community Posts'}</h3><p>Talk FEH, share rerun predictions, ask questions, and show your heroes.</p></div><a className="secondary" href={discussionUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>GitHub Discussions</a></div>
  <div className="community-account"><span>{user?'@'+user.login+(connected?' · Community posting enabled':' · Website account'): 'Everyone can read. Sign in with GitHub to join the discussion.'}</span><div>{!user?<button className="secondary" onClick={()=>window.dispatchEvent(new Event('open-owner-login'))}>Sign in</button>:!connected?<button className="secondary" disabled={busy} onClick={()=>void connect()}><Link size={16}/>Continue with GitHub</button>:null}<button className="icon-button" title="Refresh community" aria-label="Refresh community" disabled={busy||loading} onClick={()=>{void account();void load();if(post)void open(post.number,false);}}><RefreshCw size={18}/></button></div></div>
  {!connected&&user&&<p className="community-permission-note">Community posting is included with your GitHub account. Existing accounts may need to approve GitHub Discussions access once. Your encrypted connection stays enabled across future sign-ins.</p>}
  {user?.role==='owner'&&!session?.publicReady&&<aside className="community-setup"><ShieldCheck size={22}/><div><strong>Connect the public community feed</strong><p>Authorize GitHub once to let visitors read the repository’s public Discussions. Your encrypted connection will be used for these read requests.</p><button className="primary" disabled={busy} onClick={()=>void connect(true)}>Connect public feed</button></div></aside>}
  {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="community-notice">{notice}</p>}
  {compose?<><button className="secondary" onClick={back}><ArrowLeft size={16}/>Back to community</button><PostComposer key={editing?.id||user?.website_id||'draft'} categories={categories} userId={user?.website_id||''} staff={!!staff} editing={editing} onPublished={async n=>{await open(n);await load();setNotice(editing?'Post updated.':'Your post is published on GitHub Discussions.');}}/></>:post?<div className="community-reading-layout"><aside className="community-post-sidebar" aria-label="Community post list"><h3>Discussions</h3><label className="community-sidebar-search"><Search size={17}/><input aria-label="Search discussion list" type="search" placeholder="Find a post…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="primary" disabled={busy||!connected} onClick={()=>{setEditing(null);setCompose(true);}}><Plus size={16}/>New post</button><nav aria-label="Discussions">{shown.map(p=><a key={p.id} href={"?post="+p.number} aria-current={p.number===post.number?"page":undefined} onClick={e=>{if(e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();if(!busy)void open(p.number);}}}><CommunityFlair id={p.flair}/><strong>{p.title}</strong><small>@{p.author?.login||"Deleted account"} · {p.commentCount.totalCount} replies</small></a>)}</nav>{loading&&<p role="status">Loading discussions…</p>}{!loading&&!shown.length&&<p>No matching discussions.</p>}{pageInfo.hasNextPage&&<button className="secondary" disabled={loading||busy} onClick={()=>void load(pageInfo.endCursor)}>More discussions</button>}</aside><div className="community-reading-pane">
   <button className="secondary" onClick={back}><ArrowLeft size={16}/>All posts</button>
   <article className="community-post"><header><div className="community-post-tags"><CommunityFlair id={post.flair}/><span>{post.category.name}</span>{post.closed&&<span>Closed</span>}{post.locked&&<span>Locked</span>}</div><h3>{post.title}</h3><Author author={post.author} dateValue={post.createdAt}/></header><CommunityMarkdown body={post.body}/><footer><button className="secondary" aria-pressed={post.viewerHasUpvoted} disabled={busy||!connected} onClick={()=>void action('/posts/'+post.number+'/upvote',{remove:post.viewerHasUpvoted})}><ArrowUp size={17}/>{post.upvoteCount} upvotes</button><button className="secondary" aria-pressed={bookmarks.includes(post.number)} onClick={()=>bookmark(post.number)}><Bookmark size={17}/>{bookmarks.includes(post.number)?'Saved':'Save'}</button><a className="secondary" href={post.url} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>On GitHub</a>{connected&&post.viewerCanUpdate&&post.author?.login===user?.login&&<button className="secondary" onClick={()=>{setEditing(post);setCompose(true);}}>Edit post</button>}{connected&&post.viewerCanDelete&&post.author?.login===user?.login&&<button className="secondary" disabled={busy} onClick={()=>void deletePost()}>Delete post</button>}{connected&&staff&&<button className="secondary" disabled={busy} onClick={()=>setConfirmClose(true)}>{post.closed?'Reopen':'Close'} discussion</button>}</footer></article>
   {confirmClose&&<div className="community-confirm" role="alert"><p>{post.closed?'Reopen this discussion for replies?':'Close this discussion? Existing posts and replies will be preserved.'}</p><button className="secondary" onClick={()=>setConfirmClose(false)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>{setConfirmClose(false);void action('/posts/'+post.number+'/close',{reopen:post.closed});}}>Confirm</button></div>}
   <h3 className="community-replies-title"><MessageSquare size={20}/>{post.comments?.totalCount||0} replies</h3>
   <div className="community-comments">{post.comments?.nodes.map(c=><article className={'community-comment'+(c.isAnswer?' community-answer':'')} key={c.id}><Author author={c.author} dateValue={c.createdAt}/>{c.isAnswer&&<span className="community-answer-label"><CheckCircle2 size={16}/>Accepted answer</span>}<CommunityMarkdown body={c.body}/><div className="community-comment-actions">{connected&&!post.closed&&!post.locked&&<button className="secondary" onClick={()=>{setEditingReply(null);setReply('');setReplyTo(c);document.getElementById('community-reply-form')?.scrollIntoView({behavior:'smooth',block:'center'});}}>Reply</button>}{connected&&post.category.isAnswerable&&!c.isAnswer&&(staff||post.author?.login===user?.login)&&<button className="secondary" disabled={busy} onClick={()=>void action('/posts/'+post.number+'/answer',{commentId:c.id})}>Mark as answer</button>}</div>{replyActions(c)}{c.replies?.nodes.map(r=><div className="community-nested-reply" key={r.id}><Author author={r.author} dateValue={r.createdAt}/><CommunityMarkdown body={r.body}/>{replyActions(r)}</div>)}{c.replies&&c.replies.totalCount>c.replies.nodes.length&&<button className="secondary" disabled={busy} onClick={()=>void threadReplies(c)}>Load more thread replies</button>}</article>)}</div>
   {post.comments?.pageInfo.hasNextPage&&<button className="secondary" disabled={busy} onClick={()=>void moreComments()}>Load more replies</button>}
   {connected&&!post.closed&&!post.locked?<form id="community-reply-form" className="community-reply-form" onSubmit={sendReply}><h3>{editingReply?'Edit your reply':replyTo?'Reply to @'+replyTo.author?.login:'Join the discussion'}</h3>{editingReply&&<button type="button" className="secondary" onClick={()=>{setEditingReply(null);setReply('');}}>Cancel edit</button>}{replyTo&&<button type="button" className="secondary" onClick={()=>setReplyTo(null)}>Reply to post instead</button>}<CommunityEditor value={reply} onChange={setReply} disabled={busy} label="Your reply"/><button className="primary" disabled={busy||!reply.trim()}>{busy?'Publishing…':editingReply?'Save reply':'Publish reply'}</button></form>:<p>{post.closed||post.locked?'This discussion is closed to new replies.':'Continue with GitHub to reply and upvote.'}</p>}
  </div></div>:<div className="community-main-layout"><div className="community-main-feed">
   <div className="community-feed-tools"><label><Search size={18}/><input type="search" aria-label="Search community posts" placeholder="Search community posts…" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Community category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select aria-label="Community flair" value={flairFilter} onChange={e=>setFlairFilter(e.target.value)}><option value="">All flairs</option>{flairs.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select aria-label="Sort community posts" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">Recently active</option><option value="newest">Newest</option><option value="popular">Most popular</option></select><button className="icon-button" aria-label="Show saved posts" title="Saved posts on this device" aria-pressed={savedOnly} onClick={()=>setSavedOnly(!savedOnly)}><Bookmark size={18}/></button><button className="primary" disabled={busy||!connected} onClick={()=>{setEditing(null);setCompose(true);}}><Plus size={17}/>New post</button></div>
   {loading&&!posts.length?<p role="status">Loading community posts…</p>:<div className="community-feed">{shown.map(p=><article className="community-feed-card" key={p.id}><div className="community-post-tags"><CommunityFlair id={p.flair}/><span>{p.category.name}</span>{p.closed&&<span>Closed</span>}</div><a className="community-post-link" href={"?post="+p.number} onClick={e=>{if(e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();if(!busy)void open(p.number);}}}><h3>{p.title}</h3><p>{p.body.replace(/!\[[^\]]*\]\([^)]*\)/g,'').replace(/[#*`>]/g,'').slice(0,180)}</p></a><footer><Author author={p.author} dateValue={p.updatedAt}/><span><ArrowUp size={15}/>{p.upvoteCount}<MessageSquare size={15}/>{p.commentCount.totalCount}</span><button className="icon-button" aria-label={bookmarks.includes(p.number)?'Unsave post':'Save post'} aria-pressed={bookmarks.includes(p.number)} onClick={()=>bookmark(p.number)}><Bookmark size={17}/></button></footer></article>)}</div>}
   {!loading&&!shown.length&&!error&&<div className="community-empty"><MessageSquare size={36}/><h3>{savedOnly?'No saved posts in this feed':search||category?'No matching posts':'The community starts here'}</h3><p>{search||category?'Try a different search or category.':'Share a rerun prediction, ask a question, or introduce yourself.'}</p>{connected&&<button className="primary" onClick={()=>setCompose(true)}>Create a post</button>}</div>}
   {pageInfo.hasNextPage&&<button className="secondary" disabled={busy||loading} onClick={()=>void load(pageInfo.endCursor)}>{loading?'Loading…':'Load more posts'}</button>}
  </div><aside className="community-main-info"><h3>Community hub</h3><p>Choose a discussion to read the full post and join its replies.</p><button className="primary" disabled={busy||!connected} onClick={()=>{setEditing(null);setCompose(true);}}><Plus size={17}/>Create a post</button><h4>Browse by flair</h4><nav aria-label="Browse community flairs"><button className="secondary" aria-pressed={!flairFilter} onClick={()=>setFlairFilter('')}>All discussions</button>{flairs.map(f=><button className="secondary" key={f.id} aria-pressed={flairFilter===f.id} onClick={()=>setFlairFilter(f.id)}><CommunityFlair id={f.id}/></button>)}</nav><p>Share predictions, questions, resources, and showcases with the FEH community.</p><a href={discussionUrl} target="_blank" rel="noopener noreferrer">Visit GitHub Discussions <ExternalLink size={15}/></a></aside></div>}
 </section>;
}
function PostComposer({categories,userId,staff,editing,onPublished}:{categories:Category[];userId:string;staff:boolean;editing:Post|null;onPublished:(n:number)=>Promise<void>}){
 const draftKey='feh-community-draft:'+userId;
 const [initial]=useState(()=>{try{return JSON.parse(localStorage.getItem(draftKey)||'{}')||{};}catch{return {};}});
 const [flair,setFlair]=useState(editing?.flair||initial.flair||'');
 const [title,setTitle]=useState(editing?.title||initial.title||''),[body,setBody]=useState(editing?.body||initial.body||''),[category,setCategory]=useState(editing?.category.id||initial.category||categories.find(c=>c.slug==='general')?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState(false);
 useEffect(()=>{if(!editing){try{localStorage.setItem(draftKey,JSON.stringify({title,body,category,flair}));}catch{}}},[title,body,category,flair,draftKey,editing]);
 async function publish(){setBusy(true);setError('');try{const r=await communityApi<{discussion?:{number:number}}>('/posts'+(editing?'/'+editing.number:''),{title,body,categoryId:category,flair},editing?'PATCH':'POST');if(!editing){try{localStorage.removeItem(draftKey);}catch{}}await onPublished(editing?.number||r.discussion!.number);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <div className="community-composer"><h3>{editing?'Edit community post':'Create a community post'}</h3>{review?<><h3>{title}</h3><div className="community-post-tags"><CommunityFlair id={flair}/><span>{categories.find(c=>c.id===category)?.name}</span></div><CommunityMarkdown body={body}/><p className="community-permission-note">This publishes publicly to GitHub Discussions as your GitHub account.</p><div className="community-composer-actions"><button className="secondary" disabled={busy} onClick={()=>setReview(false)}>Back to editing</button><button className="primary" disabled={busy} onClick={()=>void publish()}>{busy?'Publishing…':editing?'Save changes':'Publish post'}</button></div></>:<form onSubmit={e=>{e.preventDefault();setReview(true);}}><label>Title<input required minLength={3} maxLength={200} disabled={busy} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What would you like to discuss?"/></label><label>Category<select aria-label="Category" required disabled={busy||!!editing} value={category} onChange={e=>setCategory(e.target.value)}><option value="" disabled>Choose a category</option>{categories.filter(c=>staff||c.slug!=='announcements').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Post flair<select aria-label="Post flair" required value={flair} onChange={e=>setFlair(e.target.value)} disabled={busy}><option value="" disabled>Choose a flair</option>{flairs.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><CommunityEditor value={body} onChange={setBody} disabled={busy}/><div className="community-composer-actions"><small>{editing?'Changes are saved when you publish.':'Draft saved on this device.'}</small><button className="primary" disabled={busy||!body.trim()||!category||!flair}>Review post</button></div></form>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
