import {useEffect,useRef,useState} from 'react';
import {BookOpen,Search,X} from 'lucide-react';
type Section='Schedules'|'Browsing'|'Editing'|'About';
type Entry={section:Section;question:string;answer:string;sources?:[string,string][]};
const entries:Entry[]=[
 {section:'Browsing',question:'Does the tracker update automatically?',answer:'Open pages check hero and banner data every 30 seconds while visible, and refresh when you return or reconnect. Unsaved forms pause automatic updates. Published website updates load automatically when you are not editing; your selected view and month are retained. Temporary connection failures keep the last loaded data.'},
 {section:'Schedules',question:'What is The Homepage?',answer:'The Homepage shows banners currently running, with their active dates and featured heroes in four color lanes. Multiple banners rotate in a looping carousel every 10 seconds. Use the arrows, slide indicators, swipe, or Pause; the visible fill timer counts down 10 seconds per card. Pause, touch interactions, open dialogs, and a hidden tab pause rotation. Editors enter UTC dates and times, with FEH defaults of 07:00 for the start and 06:59 for the end. Visitors see these times automatically converted to their local timezone. Entries are maintained by the owner and managers. Use the heading to switch to rerun schedules.'},
 {section:'Editing',question:'How do I manage homepage banners?',answer:'On The Homepage, choose Add new… to enter a name, start date, end date, and select existing heroes. Edit banner / slots changes the lineup. Create hero in banner opens Add Hero and attaches the saved hero to that banner. Banner membership is separate from a hero’s rerun month. Upcoming and ended banners are available in the editor section.'},
 {section:'Schedules',question:'Which schedule should I choose?',answer:'General is for the end-of-month rotation. Remix has its own older-hero reruns. Monthly Revival separates Legendary and Mythic revivals within each month. Rerun Waitlist holds heroes without an assigned rerun month. Open the heading at the top to switch views.'},
 {section:'Schedules',question:'What is General Schedule?',answer:'This is the tracker’s end-of-month banner view for Legendary, Mythic, Emblem, and Chosen Heroes. Each column is a recorded month and each row is a hero color. Check the actual event announcement for its lineup and exact dates.',sources:[['FEH Wiki: banner archive','https://feheroes.fandom.com/wiki/Category:Legendary/Mythic/Emblem_Hero_summoning_events']]},
 {section:'Schedules',question:'What is Remix Schedule?',answer:'Remix keeps older heroes returning on Remix banners in a separate month-by-month view. A listed return does not itself announce a new skill upgrade. Read the hero’s note and the event announcement for context.',sources:[['FEH Wiki: Remix archive','https://feheroes.fandom.com/wiki/Summoning_event_archive/Legendary_%26_Mythic_Hero_Remix']]},
 {section:'Schedules',question:'What is Monthly Revival Schedule?',answer:'Monthly Revival groups older Legendary and Mythic reruns by month, with separate Legendary Revival and Mythic Revival columns. These entries are separate from General and Remix, and from the game’s Weekly Revival series.',sources:[['FEH Wiki: Monthly Revival archive','https://feheroes.fandom.com/wiki/Summoning_event_archive/Monthly_Revival']]},
 {section:'Schedules',question:'What is Rerun Waitlist?',answer:'Waitlist holds heroes without a recorded rerun month. It uses the same four color lanes and expands horizontally as more heroes are added. Scroll sideways or swipe to browse. Being listed does not promise a particular banner or return date.'},
 {section:'Schedules',question:'How reliable is a recorded month?',answer:'Entries are maintained manually by the owner and managers. A month is a planning window, not an exact start day. Read the hero’s note for an announcement source, expectation, or uncertainty, then check the in-game notice for final information.',sources:[['Nintendo: FEH news','https://fire-emblem-heroes.com/en/topics/']]},
 {section:'Browsing',question:'What do the pool labels mean?',answer:'General Pool groups ordinary general-pool entries. Limited Pool groups Special Heroes and heroes outside the ordinary pool, including Rearmed, Attuned, Aided, Entwined, Vista, and Chosen. L/M/E Pool groups Legendary, Mythic, and Emblem entries. Pool selection is independent of hero type; these tracker labels do not replace a banner’s actual summoning availability.'},
 {section:'Browsing',question:'What do the icons and hero type labels mean?',answer:'The icon and text identify the recorded hero type. Legendary and Chosen display Wind, Earth, Fire, or Water; Mythic displays Anima, Astra, Light, or Dark. Emblem, Duo, Harmonized, Rearmed, Attuned, Aided, Entwined, Vista, General, and Special have their own icons. Pool icons identify the separate pool grouping.',sources:[['Nintendo: Legendary and Mythic blessings','https://new-guide.fire-emblem-heroes.com/en-US/feh-1170.html']]},
 {section:'Browsing',question:'How do I search and filter?',answer:'Choose a schedule, then search a hero’s name or title. Hero type narrows the list; Advanced filters combine type, color, and pool. Reset filters and clear the search if a hero appears missing. Filtering applies to the selected schedule.'},
 {section:'Browsing',question:'How do I navigate months and see details?',answer:'Use the slider or month navigation buttons on dated views. Hover over a hero on desktop for a preview, or click / tap for full Hero Details, including its title, tags, pool, editor note, and update information. Waitlist has no month slider.'},
 {section:'Browsing',question:'How does the layout adapt to my screen?',answer:'Rows and portraits adjust to available browser space, with minimum sizes to keep information readable. Dated columns and Waitlist lanes scroll horizontally when needed. Compact view makes cards smaller and hides their tags; details remain available by hovering or tapping.'},
 {section:'Editing',question:'Who can edit the tracker?',answer:'The owner and authorized managers can add, edit, delete, upload portraits, and write hero notes after signing in with their own account. Only the owner manages editor access. The Managers panel requires an existing confirmed account and does not send invitations.'},
 {section:'Editing',question:'How do I add a hero or change its rerun month?',answer:'Open Add hero, or choose Edit hero from Hero Details. Enter the name, title, type, blessing if applicable, color, and pool. Check Demote only for a 4–5★ summonable demote hero; this appears in Hero Details and hover previews. Select General, Remix, or Monthly Revival and supply a month. Choose Rerun Waitlist when no month is available, or enable Skip next rerun month to save an uncertain EoM return to Waitlist without entering a date. Homepage banner membership stays intact. Save to publish the change; moving into Waitlist clears the month.'},
 {section:'Editing',question:'What should I put in a hero note?',answer:'Include the announcement source, banner context, expected timing, or information that is still uncertain. Notes are visible in Hero Details and previews, so write them for visitors. Both the owner and managers can update notes.'},
 {section:'Editing',question:'How do portrait uploads and image links work?',answer:'Use a PNG, JPG, or WebP image up to 3 MB. Choose a file, drag and drop it, or paste a copied image. A supported direct FEH Wiki / Fandom image URL can also be imported. Wait for the preview before saving. If the host blocks import, download the image and upload the file.'},
 {section:'About',question:'Can I install the tracker on my phone?',answer:'Use Install app in the footer. On Android, open in Chrome and use the install option when available. On iPhone or iPad, use Safari → Share → Add to Home Screen, with Open as Web App enabled if offered. Current schedules and editing need internet access.',sources:[['Apple: add a web app','https://support.apple.com/en-hk/guide/iphone/iphea86e5236/ios']]},
 {section:'About',question:'Who made this website?',answer:'Clustifle made this unofficial fan tracker, originally on ChatGPT Sites and later migrated to GitHub Pages with Supabase. Artwork belongs to Nintendo / INTELLIGENT SYSTEMS; Champions typography is from UEFA. About this page contains credits, and the footer links to Clustifle’s social pages.'}
];
export default function FaqHelp(){
 const dialog=useRef<HTMLDialogElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [query,setQuery]=useState(''),[section,setSection]=useState<Section|'All'>('All'),[closing,setClosing]=useState(false);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 function close(){if(closing)return;setClosing(true);timer.current=setTimeout(()=>{dialog.current?.close();setClosing(false);},window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:220);}
 const filtered=entries.filter(e=>(section==='All'||section===e.section)&&(e.question+' '+e.answer).toLowerCase().includes(query.trim().toLowerCase()));
 return <><button className="about-link" onClick={()=>{if(timer.current)clearTimeout(timer.current);setClosing(false);setQuery('');setSection('All');dialog.current?.showModal();}}>FAQ</button><dialog ref={dialog} className={'faq-popup'+(closing?' is-closing':'')} aria-labelledby="faq-title" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="faq-header"><div className="dialog-top"><BookOpen aria-hidden="true"/><button className="icon-button" aria-label="Close FAQ" onClick={close}><X/></button></div><h2 id="faq-title">FAQ</h2><p>Your guide to schedules, heroes, and editing.</p><label className="faq-search"><Search size={18} aria-hidden="true"/><input type="search" aria-label="Search FAQ" placeholder="Search schedules, pools, portraits…" value={query} onChange={e=>setQuery(e.target.value)}/></label><nav className="faq-sections" aria-label="FAQ topics">{(['All','Schedules','Browsing','Editing','About'] as const).map(topic=><button key={topic} aria-pressed={section===topic} onClick={()=>setSection(topic)}>{topic}</button>)}</nav></div><div className="faq-content"><p className="faq-context">Choose a topic or search for an answer. Game references are linked below; entries are maintained by editors.</p><p className="faq-count" role="status">{filtered.length} {filtered.length===1?'answer':'answers'}</p>{filtered.map(e=><details key={e.question} className="faq-entry" open={query.trim()?true:undefined}><summary>{e.question}</summary><div><p>{e.answer}</p>{e.sources&&<nav aria-label={'Sources for '+e.question}>{e.sources.map(([name,url])=><a key={url} href={url} target="_blank" rel="noopener noreferrer">{name} ↗</a>)}</nav>}</div></details>)}{!filtered.length&&<p className="faq-empty">No matching answers. Try another topic or search for “pool” or “portrait”.</p>}</div></dialog></>;
}
