import {useRef,useState} from 'react';
import {BookOpen,Search,X} from 'lucide-react';
type Entry={question:string;answer:string;sources?:[string,string][]};
const entries:Entry[]=[
 {question:'What is General Schedule (End of Month Banner Schedule)?',answer:'This tracker uses General Schedule for the end-of-month banner rotation covering Legendary, Mythic, Emblem, and Chosen Heroes. A hero is placed under the month recorded by an editor. It is separate from Remix and Monthly Revival; check the actual banner announcement for its lineup and dates.',sources:[['FEH Wiki: banner archive','https://feheroes.fandom.com/wiki/Category:Legendary/Mythic/Emblem_Hero_summoning_events']]},
 {question:'What is Remix Schedule?',answer:'Remix Schedule tracks older heroes returning on Remix banners, in its own month-by-month space. Legendary & Mythic Hero Remix events are a distinct banner series. A rerun entry means the hero is returning; it does not by itself announce a new skill upgrade.',sources:[['FEH Wiki: Remix archive','https://feheroes.fandom.com/wiki/Summoning_event_archive/Legendary_%26_Mythic_Hero_Remix'],['Nintendo: Remix update','https://fire-emblem-heroes.com/en-gb/sp/topics/index.html?id=detail-20250311']]},
 {question:'What is Monthly Legendary / Mythic Revival?',answer:'Monthly Revival Schedule tracks older Legendary and Mythic Heroes on their revival banners. Each month is grouped into Legendary Revival and Mythic Revival columns. These are separate from this tracker’s General and Remix views, and from the game’s Weekly Revival banner series.',sources:[['FEH Wiki: Monthly Revival archive','https://feheroes.fandom.com/wiki/Summoning_event_archive/Monthly_Revival']]},
 {question:'What is Rerun Waitlist?',answer:'Rerun Waitlist is this website’s editor-maintained list for heroes released through New Heroes and Special Heroes banners. It has color rows but no assigned rerun month. Being listed is not an official promise of a rerun or a date; open Hero Details for the editor’s context.'},
 {question:'What do Confirmed, Predicted, Uncertain, and Unknown mean?',answer:'These are editorial labels used by this tracker. Confirmed means an editor has recorded announced information. Predicted means an expected return based on a pattern or informed guess. Uncertain means the timing or information remains doubtful. Unknown means no rerun timing is recorded. Predictions can change; read the hero’s note for evidence.'},
 {question:'Are the months exact dates, and is the tracker automatically updated?',answer:'A month identifies the recorded rerun window, not an exact start day. The owner and authorized managers maintain entries manually. Check the in-game notification and event calendar for final dates, times, lineup, and availability; this unofficial tracker can lag behind announcements.',sources:[['Nintendo: FEH news','https://fire-emblem-heroes.com/en/topics/']]},
 {question:'What are General Pool and Limited Pool?',answer:'These are this tracker’s grouping labels. Limited Pool groups Legendary, Mythic, and the supported special hero types, including Special Heroes. General Pool is the label for general-pool entries. This grouping does not replace the game’s banner-specific summoning availability or appearance rates; check the individual banner before summoning.'},
 {question:'What do hero type and blessing tags mean?',answer:'Type tags identify Legendary, Mythic, Emblem, Chosen, Rearmed, Attuned, Aided, Entwined, Duo, Harmonized, or Vista. Legendary elements are Wind, Earth, Fire, and Water; Mythic elements are Anima, Astra, Light, and Dark. This editor also offers the four elemental tags for Chosen. Emblem uses a red-blue gradient. Tags describe the recorded hero, not a guarantee of banner availability.',sources:[['Nintendo: blessings guide','https://new-guide.fire-emblem-heroes.com/en-US/feh-1170.html']]},
 {question:'How do I find a hero or use filters?',answer:'Choose a schedule first, then use Find a hero and the Hero type dropdown. Advanced filters combine hero type, color, rerun status, and pool. If an entry seems missing, clear the search and reset filters. Red, Blue, Green, and Colorless rows organize the heroes by their recorded color.'},
 {question:'How do the month slider, Compact view, and Hero Details work?',answer:'Move the month slider or use the month navigation controls to browse scheduled months. Waitlist has no month slider. Compact view reduces portrait and column sizes and hides card tags. Hover over a hero on desktop for a preview, or click / tap to open full Hero Details with its tags and note.'},
 {question:'Who can edit heroes and add notes?',answer:'Anyone can view the tracker without signing in. Only the owner and authorized managers can add, edit, delete, upload portraits, and write hero notes after signing in. The owner controls manager access. If access is denied, ask the owner to check the authorized account email.'},
 {question:'How do I upload or import a hero portrait?',answer:'In Add / Edit Hero, choose a PNG, JPG, or WebP file up to 3 MB, drag and drop an image, or paste a copied image. For wiki imports, paste a direct image URL rather than the wiki article URL and wait for the preview. If the host blocks the import, download the portrait and upload the file instead.'},
 {question:'Can I install this tracker on my phone?',answer:'Use Install app in the footer. On Android, open the site in Chrome and use the install option when available. On iPhone or iPad, open it in Safari, choose Share → Add to Home Screen, and enable Open as Web App if shown. Internet access is needed for current schedules and editing.',sources:[['Apple: add a web app','https://support.apple.com/en-hk/guide/iphone/iphea86e5236/ios']]},
 {question:'Is this an official Nintendo website?',answer:'No. This is an unofficial fan tracker made by Clustifle. Fire Emblem Heroes artwork belongs to Nintendo / INTELLIGENT SYSTEMS. See About this page for credits. Game information may change; linked sources and in-game announcements take priority.'}
];
export default function FaqHelp(){
 const dialog=useRef<HTMLDialogElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [query,setQuery]=useState(''),[closing,setClosing]=useState(false);
 function close(){if(closing)return;setClosing(true);timer.current=setTimeout(()=>{dialog.current?.close();setClosing(false);},window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:220);}
 const filtered=entries.filter(e=>(e.question+' '+e.answer).toLowerCase().includes(query.trim().toLowerCase()));
 return <><button className="about-link" onClick={()=>{if(timer.current)clearTimeout(timer.current);setClosing(false);setQuery('');dialog.current?.showModal();}}>FAQ Help</button><dialog ref={dialog} className={'faq-popup'+(closing?' is-closing':'')} aria-labelledby="faq-title" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="faq-header"><div className="dialog-top"><BookOpen aria-hidden="true"/><button className="icon-button" aria-label="Close FAQ Help" onClick={close}><X/></button></div><h2 id="faq-title">FAQ Help</h2><p>Understand the banners. Find your next rerun.</p><label className="faq-search"><Search size={18} aria-hidden="true"/><input type="search" aria-label="Search FAQ" placeholder="Search schedules, tags, portraits…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="faq-content"><p className="faq-context">Banner references researched 3 October 2026. Tracker labels and predictions are maintained by editors.</p><p className="faq-count" role="status">{filtered.length} {filtered.length===1?'answer':'answers'}</p>{filtered.map(e=><details key={e.question} className="faq-entry" open={query.trim()?true:undefined}><summary>{e.question}</summary><div><p>{e.answer}</p>{e.sources&&<nav aria-label={'Sources for '+e.question}>{e.sources.map(([name,url])=><a key={url} href={url} target="_blank" rel="noopener noreferrer">{name} ↗</a>)}</nav>}</div></details>)}{!filtered.length&&<p className="faq-empty">No matching answers. Try “Remix”, “status”, or “portrait”.</p>}</div></dialog></>;
}
