import {useEffect,useState} from 'react';
import {RefreshCw,ExternalLink,Eye,EyeOff,LockKeyhole,LockKeyholeOpen} from 'lucide-react';
import {communityApi,type CommunitySession,type Post,type Comment,type PageInfo} from './community-api';
import {ForumModerators} from './Community';
import ForumRules from './ForumRules';
import CommunityMarkdown from './CommunityMarkdown';
import CommunityFlair from './CommunityFlair';
import './Community.css';
type Audit={id:number;post_number:number;target_id:string;action:string;reason:string;actor_login:string;created_at:string};
export default function ForumManagement(){const [session,setSession]=useState<CommunitySession|null>(null),[tab,setTab]=useState('posts'),[posts,setPosts]=useState<Post[]>([]),[page,setPage]=useState<PageInfo>({hasNextPage:false}),[selected,setSelected]=useState<Post|null>(null),[history,setHistory]=useState<Audit[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState<{post:Post;comment?:Comment;kind:'visibility'|'status'}|null>(null),[reason,setReason]=useState('');
 async function load(after?:string){setBusy(true);setError('');try{const r=await communityApi<{posts:Post[];pageInfo:PageInfo}>('/posts?moderation=1'+(after?'&after='+encodeURIComponent(after):''));setPosts(old=>after?[...old,...r.posts.filter(p=>!old.some(x=>x.id===p.id))]:r.posts);setPage(r.pageInfo);const audit=await communityApi<{actions:Audit[]}>('/moderation/history');setHistory(audit.actions);}catch(e){setError(e instanceof Error?e.message:'Could not load Forum management.');}finally{setBusy(false);}}
 useEffect(()=>{let alive=true;void communityApi<CommunitySession>('/session').then(s=>{if(alive){setSession(s);if(s.user&&['owner','manager','moderator'].includes(s.user.role))void load();}}).catch(e=>setError(String(e)));return()=>{alive=false;};},[]);
 async function inspect(number:number){setBusy(true);try{const r=await communityApi<{post:Post}>('/posts/'+number+'?moderation=1');setSelected(r.post);}catch(e){setError(e instanceof Error?e.message:'Could not open post.');}finally{setBusy(false);}}
 function request(post:Post,kind:'visibility'|'status',comment?:Comment){setConfirm({post,kind,comment});setReason('');}
 async function apply(){if(!confirm||reason.trim().length<3)return;setBusy(true);setError('');try{const c=confirm;if(c.kind==='visibility')await communityApi('/moderation',{number:c.post.number,commentId:c.comment?.id,hidden:!(c.comment?.forumHidden??c.post.forumHidden),reason:reason.trim()});else await communityApi('/posts/'+c.post.number+'/close',{reopen:c.post.closed,reason:reason.trim()});setConfirm(null);setNotice('Moderation action saved.');await load();if(selected)await inspect(selected.number);}catch(e){setError(e instanceof Error?e.message:'Could not apply action.');}finally{setBusy(false);}}
 const staff=!!session?.user&&['owner','manager','moderator'].includes(session.user.role),shown=posts.filter(p=>(!search||(p.title+' '+p.author?.login).toLowerCase().includes(search.toLowerCase()))&&(status==='all'||status==='hidden'&&p.forumHidden||status==='closed'&&p.closed||status==='visible'&&!p.forumHidden));
 function controls(p:Post,c?:Comment){const hidden=c?.forumHidden??p.forumHidden;return <button className="secondary" disabled={busy} onClick={()=>request(p,'visibility',c)}>{hidden?<Eye size={16}/>:<EyeOff size={16}/>} {hidden?'Restore':'Hide in Forum'}</button>;}
 function comment(c:Comment){return <article className="forum-review-reply" key={c.id}><strong>@{c.author?.login||'Deleted account'}{c.forumHidden?' · Hidden':''}</strong><CommunityMarkdown body={c.body}/>{selected&&controls(selected,c)}{c.replies?.nodes.map(comment)}{c.replies?.pageInfo?.hasNextPage&&selected&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await communityApi<{replies:NonNullable<Comment['replies']>}>('/posts/'+selected.number+'/replies?moderation=1&commentId='+encodeURIComponent(c.id)+'&after='+encodeURIComponent(c.replies?.pageInfo?.endCursor||''));setSelected(old=>old?.comments?{...old,comments:{...old.comments,nodes:old.comments.nodes.map(x=>x.id===c.id?{...x,replies:{...r.replies,nodes:[...(x.replies?.nodes||[]),...r.replies.nodes]}}:x)}}:old);}catch(e){setError(String(e));}finally{setBusy(false);}}}>More thread replies</button>}</article>;}
 if(!session)return <p role="status">{error||'Checking Forum access…'}</p>;if(!staff)return <p role="alert">Forum staff access is required.</p>;
 return <section className="community-workspace community-management forum-manager"><header className="forum-manager-header"><div><h3>Forum management</h3><p>Review discussions, enforce Forum Rules, and track moderation actions.</p></div><button className="icon-button" title="Refresh Forum" aria-label="Refresh Forum" disabled={busy} onClick={()=>void load()}><RefreshCw size={19}/></button></header><div className="forum-manager-summary"><span>{posts.length} loaded posts</span><span>{posts.filter(p=>p.forumHidden).length} hidden</span><span>{posts.filter(p=>p.closed).length} closed</span></div><div className="adm-tabs" role="tablist" aria-label="Forum tools">{['posts','history','rules',...(session.user?.role==='owner'?['moderators']:[])].map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t==='posts'?'Posts & Replies':t[0].toUpperCase()+t.slice(1)}</button>)}</div><p className="forum-scope-note">Hide/restore changes visibility on this website. Content remains on GitHub. Closing/reopening a discussion requires your GitHub repository permissions.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {tab==='rules'?<ForumRules/>:tab==='moderators'?<ForumModerators/>:tab==='history'?<div className="forum-audit">{history.length?history.map(a=><article key={a.id}><strong>{a.action} · Post #{a.post_number}</strong><p>{a.reason}</p><small>@{a.actor_login} · {new Date(a.created_at).toLocaleString()}</small></article>):<p>No moderation actions yet.</p>}</div>:<><div className="forum-manager-filters"><input aria-label="Search forum moderation posts" placeholder="Search loaded posts or authors…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Moderation status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="visible">Visible</option><option value="hidden">Hidden</option><option value="closed">Closed</option></select></div><div className="forum-manager-posts">{shown.map(p=><article key={p.id}><CommunityFlair id={p.flair}/><h4>{p.title}</h4><p>@{p.author?.login||'Deleted account'} · {p.forumHidden?'Hidden':'Visible'} · {p.closed?'Closed':'Open'} · {p.commentCount.totalCount} replies</p><div className="forum-manager-actions"><button className="secondary" disabled={busy} onClick={()=>void inspect(p.number)}>Review replies</button>{controls(p)}<button className="secondary" disabled={busy||!session.connected} onClick={()=>request(p,'status')}>{p.closed?<LockKeyholeOpen size={16}/>:<LockKeyhole size={16}/>} {p.closed?'Reopen':'Close'}</button><a href={p.url} target="_blank" rel="noopener noreferrer">On GitHub <ExternalLink size={15}/></a></div></article>)}</div>{!shown.length&&<p>{busy?'Loading posts…':'No matching posts.'}</p>}{page.hasNextPage&&<button className="secondary" disabled={busy} onClick={()=>void load(page.endCursor)}>Load more posts</button>}{selected&&<section className="forum-review"><header><h3>Review: {selected.title}</h3><button className="secondary" onClick={()=>setSelected(null)}>Close review</button></header><CommunityMarkdown body={selected.body}/>{selected.comments?.nodes.map(comment)}{selected.comments?.pageInfo.hasNextPage&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await communityApi<{post:Post}>('/posts/'+selected.number+'?moderation=1&after='+encodeURIComponent(selected.comments!.pageInfo.endCursor||''));setSelected({...r.post,comments:{...r.post.comments!,nodes:[...selected.comments!.nodes,...r.post.comments!.nodes]}});}catch(e){setError(String(e));}finally{setBusy(false);}}}>More replies</button>}</section>}</>}
 {confirm&&<section className="forum-moderation-confirm" role="region" aria-label="Confirm moderation action"><h4>{confirm.kind==='status'?(confirm.post.closed?'Reopen':'Close'):(confirm.comment?.forumHidden??confirm.post.forumHidden)?'Restore visibility':'Hide in Forum'} · {confirm.comment?'Reply':'Post #'+confirm.post.number}</h4><label>Reason<textarea aria-label="Moderation reason" minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Rule and reason for this action…"/></label><div className="forum-manager-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button className="primary" disabled={busy||reason.trim().length<3} onClick={()=>void apply()}>Confirm action</button></div></section>}
 </section>;
}
