import {useEffect,useRef,useState} from 'react';
import {Pencil,X} from 'lucide-react';
import {supabase,portraitUrl} from './static-data';
import {goTo,viewUrl} from './routes';
import {bannerTiming,bannerStatusTag} from './banner-time';
import useBannerClock from './useBannerClock';
import {useAutoRefresh} from './useAutoRefresh';
type Hero={id:string;name:string;color:string;portrait?:string|null};
type Revival={month:string;title:string;ongoing:boolean;coming_soon:boolean;home_featured?:boolean;starts_on:string|null;ends_on:string|null;starts_time:string;ends_time:string;hero_1:string|null;hero_2:string|null;hero_3:string|null;hero_4:string|null};
const kinds=[{table:'forging_bonds_revivals',label:'New Heroes Revival',view:'Forging Bonds Revival'},{table:'hall_of_forms_revivals',label:'Hall of Forms Revival',view:'Hall of Forms Revival'}];
const monthLabel=(month:string)=>new Date(month+'T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'});
export default function HomeRevivals({heroes,canEdit}:{heroes:Hero[];canEdit:boolean}){
 const [groups,setGroups]=useState<Revival[][]>([[],[]]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState<number|null>(null),[selected,setSelected]=useState(''),[saving,setSaving]=useState(false);
 const editor=useRef<HTMLDialogElement>(null);
 const now=useBannerClock(groups.flat().filter(e=>e.starts_on&&e.ends_on).map(e=>({start:Date.parse(e.starts_on+'T'+(e.starts_time||'07:00')+'Z'),end:Date.parse(e.ends_on+'T'+(e.ends_time||'06:59')+'Z')})));
 async function load(){const results=await Promise.all(kinds.map(k=>supabase.from(k.table).select('*').gte('month','2025-10-01').lte('month','2029-10-01').order('month')));if(results.some(r=>r.error))setError('Could not load revivals.');else{setGroups(results.map(r=>r.data||[]));setError('');}setLoading(false);}
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('revivals-change',refresh);return()=>window.removeEventListener('revivals-change',refresh);},[]);
 useAutoRefresh(load);
 useEffect(()=>{if(!canEdit){editor.current?.close();setEditing(null);}},[canEdit]);
 function status(e:Revival){if(!e.ongoing&&!e.coming_soon)return null;if(!e.starts_on||!e.ends_on)return e.coming_soon?'Coming soon':null;return bannerStatusTag(bannerTiming(e.starts_on,e.ends_on,now,e.starts_time||'07:00',e.ends_time||'06:59'),e.coming_soon);}
 function choice(rows:Revival[]){return rows.find(e=>e.home_featured&&status(e))||rows.find(e=>e.ongoing&&status(e))||rows.find(e=>e.coming_soon&&status(e));}
 function open(index:number){setEditing(index);setSelected(groups[index].find(e=>e.home_featured)?.month||'');setError('');editor.current?.showModal();}
 async function save(e:React.FormEvent){e.preventDefault();if(editing===null)return;setSaving(true);const {error}=await supabase.rpc('set_home_revival',{revival_kind:kinds[editing].table,revival_month:selected||null});if(error)setError('Could not save the selected month. Please try again.');else{editor.current?.close();setEditing(null);window.dispatchEvent(new Event('revivals-change'));}setSaving(false);}
 return <section className="home-revivals" aria-labelledby="home-revivals-title"><h2 id="home-revivals-title">Revival</h2>{loading&&<p role="status">Loading revivals…</p>}{error&&editing===null&&<p role="alert">{error} <button onClick={()=>void load()}>Try again</button></p>}<div className="home-revival-grid">{kinds.map((kind,index)=>{const event=choice(groups[index]);return <article className="home-revival-card" key={kind.table}><a className="home-revival-link" href={viewUrl(kind.view,event?.month.slice(0,7)||'')} onClick={e=>{if(e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();goTo(viewUrl(kind.view,event?.month.slice(0,7)||''));}}}>{event&&<p className="home-banner-countdown" role="timer" aria-live="off">{status(event)}</p>}<span className="home-revival-kind">{kind.label}</span><h3>{event?.title||'No active revival listed'}</h3>{event&&<p className="home-revival-month">{monthLabel(event.month)}</p>}<div className="home-revival-heroes">{event&&(['hero_1','hero_2','hero_3','hero_4'] as const).map(key=>{const hero=heroes.find(h=>h.id===event[key]);return <span key={key} className={'home-revival-portrait '+(hero?.color.toLowerCase()||'empty')}>{hero?.portrait?<img src={portraitUrl(hero.portrait)} alt={hero.name} loading="lazy" decoding="async"/>:<span>{hero?.name||'—'}</span>}</span>;})}</div></a>{canEdit&&<button className="home-revival-edit" title="Select revival month" aria-label={'Select '+kind.label+' month'} onClick={()=>open(index)}><Pencil size={18}/></button>}</article>;})}</div><dialog className="fb-editor home-revival-editor" ref={editor} aria-labelledby="home-revival-editor-title" onCancel={e=>{if(saving)e.preventDefault();else setEditing(null);}}><form onSubmit={save}><div className="dialog-top"><h2 id="home-revival-editor-title">Select revival month</h2><button type="button" className="icon-button" aria-label="Close month selection" disabled={saving} onClick={()=>{editor.current?.close();setEditing(null);}}><X/></button></div>{editing!==null&&<><label>{kinds[editing].label}<select value={selected} disabled={saving} onChange={e=>setSelected(e.target.value)}><option value="">Automatic · ongoing or coming soon</option>{groups[editing].map(event=><option value={event.month} key={event.month}>{monthLabel(event.month)} · {event.title}</option>)}</select></label><p>The selected month is featured while marked Currently ongoing or Coming soon. When it ends, the next eligible revival appears automatically.</p></>}{error&&<p role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>{editor.current?.close();setEditing(null);}}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save selection'}</button></div></form></dialog></section>;
}
