import {useEffect,useRef,useState} from 'react';
import {Download,X} from 'lucide-react';
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function InstallApp(){
 const [prompt,setPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const media=window.matchMedia('(display-mode: standalone)');const update=()=>setInstalled(media.matches||(navigator as Navigator&{standalone?:boolean}).standalone===true);update();media.addEventListener('change',update);const ready=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPrompt);};const done=()=>{setInstalled(true);setPrompt(null);dialog.current?.close();};window.addEventListener('beforeinstallprompt',ready);window.addEventListener('appinstalled',done);return()=>{media.removeEventListener('change',update);window.removeEventListener('beforeinstallprompt',ready);window.removeEventListener('appinstalled',done);};},[]);
 async function install(){if(!prompt)return;setBusy(true);setMessage('');try{await prompt.prompt();const choice=await prompt.userChoice;setPrompt(null);setMessage(choice.outcome==='accepted'?'Installation requested. Follow your browser instructions.':'You can install later from your browser menu.');}catch{setPrompt(null);setMessage('Use your browser menu to add this app to your Home Screen.');}finally{setBusy(false);}}
 if(installed)return null;
 return <><button className="about-link" onClick={()=>{setMessage('');dialog.current?.showModal();}}>Install app</button><dialog className="install-popup" ref={dialog} aria-labelledby="install-title" onClick={e=>{if(e.target===e.currentTarget&&!busy)dialog.current?.close();}}><div className="dialog-top"><Download/><button className="icon-button" aria-label="Close install instructions" disabled={busy} onClick={()=>dialog.current?.close()}><X/></button></div><h2 id="install-title">FEH Rerun on your Home Screen</h2><p>Open the tracker like an app, with its own icon and window.</p>{prompt&&<button className="primary" disabled={busy} onClick={()=>void install()}>{busy?'Opening installer…':'Install app'}</button>}<section><h3>Android</h3><p>Open this website in Chrome. Use Install app here when available, or the browser menu → Install app / Add to Home screen.</p></section><section><h3>iPhone / iPad</h3><p>Open this website in Safari. Tap Share → Add to Home Screen, enable Open as Web App if shown, then tap Add.</p></section><p className="install-note">An internet connection is needed for current schedules and editing.</p>{message&&<p role="status">{message}</p>}</dialog></>;
}
