import {assetUrl} from './static-data';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function InstallApp(){
 const [prompt,setPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const open=()=>{setMessage('');dialog.current?.showModal();};window.addEventListener('open-install-app',open);return()=>window.removeEventListener('open-install-app',open);},[]);
 useEffect(()=>{const media=window.matchMedia('(display-mode: standalone)');const update=()=>setInstalled(media.matches||(navigator as Navigator&{standalone?:boolean}).standalone===true);update();media.addEventListener('change',update);const ready=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPrompt);};const done=()=>{setInstalled(true);setPrompt(null);dialog.current?.close();};window.addEventListener('beforeinstallprompt',ready);window.addEventListener('appinstalled',done);return()=>{media.removeEventListener('change',update);window.removeEventListener('beforeinstallprompt',ready);window.removeEventListener('appinstalled',done);};},[]);
 async function install(){if(!prompt)return;setBusy(true);setMessage('');try{await prompt.prompt();const choice=await prompt.userChoice;setPrompt(null);setMessage(choice.outcome==='accepted'?'Installation requested. Follow your browser instructions.':'You can install later from your browser menu.');}catch{setPrompt(null);setMessage('Use your browser menu to add this app to your Home Screen.');}finally{setBusy(false);}}
 const help=/iPad|iPhone|iPod/.test(navigator.userAgent)?'In Safari, tap Share → Add to Home Screen.':'Use your browser menu → Install app or Add to Home screen. If unavailable, open this site in Chrome or Edge.';
 return <dialog className="install-popup install-minimal" ref={dialog} aria-labelledby="install-title" onCancel={e=>{if(busy)e.preventDefault();}} onClick={e=>{if(e.target===e.currentTarget&&!busy)dialog.current?.close();}}><button className="icon-button install-close" aria-label="Close install instructions" disabled={busy} onClick={()=>dialog.current?.close()}><X/></button><img className="install-app-icon" src={assetUrl('icons/app-192.png?v=2')} alt="FEH Rerun app"/><h2 id="install-title">FEH Rerun Schedule</h2><p>{installed?'Already installed on this device.':'Add the tracker to your Home Screen or desktop.'}</p><button className="primary" disabled={busy||installed} onClick={()=>prompt?void install():setMessage(help)}>{installed?'Installed':busy?'Opening…':'Install'}</button>{message&&<p role="status" className="install-status">{message}</p>}</dialog>;
}
