import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {supabase} from './static-data';
export default function Managers(){
 const dialog=useRef<HTMLDialogElement>(null);
 const [emails,setEmails]=useState<string[]>([]),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){const {data,error}=await supabase.rpc('list_tracker_managers');if(error)throw error;setEmails((data||[]).map((m:{email:string})=>m.email));}
 useEffect(()=>{const open=()=>{setEmail('');setError('');setNotice('');dialog.current?.showModal();void load().catch(e=>setError(e.message));};window.addEventListener('open-managers',open);return()=>window.removeEventListener('open-managers',open);},[]);
 async function update(value:string,enabled:boolean){setBusy(true);setError('');setNotice('');try{const {error}=await supabase.rpc('set_tracker_manager',{manager_email:value.trim().toLowerCase(),enabled});if(error)throw error;await load();setEmail('');setNotice(enabled?'Manager added. They can sign in with their own account.':'Manager access removed.');}catch(e){setError(e instanceof Error?e.message:'Could not change access.');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="manager-dialog" aria-labelledby="managers-title" onCancel={e=>{if(busy)e.preventDefault();}}><div className="dialog-top"><h2 id="managers-title">Manage managers</h2><button className="icon-button" aria-label="Close managers" disabled={busy} onClick={()=>dialog.current?.close()}><X/></button></div><p className="manager-help">Managers can add, edit, and delete heroes and upload portraits. Only the Owner can change manager access.</p><div className="manager-owner"><strong>Owner</strong><span>shyguyvn@gmail.com</span></div><form onSubmit={e=>{e.preventDefault();void update(email,true);}}><label>Manager email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} disabled={busy} placeholder="Enter manager email"/></label><p className="manager-help">The email must belong to a confirmed account in Supabase Authentication. No invitation email is sent.</p><button className="primary" disabled={busy}>{busy?'Updating…':'Add Manager'}</button></form><ul className="manager-list">{emails.map(value=><li key={value}><div><span>{value}</span><small>Manager</small></div><button className="secondary" disabled={busy} onClick={()=>void update(value,false)}>Remove access</button></li>)}</ul>{!emails.length&&<p className="manager-help">No managers added yet.</p>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}</dialog>;
}
