import {useEffect,useRef} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
const short=(month:string)=>new Date(month+'-01T12:00:00').toLocaleDateString('en-US',{month:'short',year:'2-digit'});
const full=(month:string)=>new Date(month+'-01T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'});
export default function MonthNavigator({months,selected,current,onSelect,currentLabel='Current month'}:{months:string[];selected:string;current:string;onSelect:(index:number)=>void;currentLabel?:string}){
 const strip=useRef<HTMLDivElement>(null),index=Math.max(0,months.indexOf(selected));
 useEffect(()=>{const row=strip.current,button=row?.children[index] as HTMLElement|undefined;if(row&&button)row.scrollTo({left:button.offsetLeft-(row.clientWidth-button.offsetWidth)/2,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[selected,index,months.length]);
 return <section className="month-control month-navigator" aria-label="Month navigation"><div className="month-strip-heading"><span>Browse months</span><button className="month-current" onClick={()=>onSelect(months.indexOf(current))}>{currentLabel}</button></div><div className="month-strip-row"><button className="month-arrow" aria-label="Previous month" disabled={index===0} onClick={()=>onSelect(index-1)}><ChevronLeft size={24}/></button><div className="month-strip" ref={strip} aria-label="Choose rerun month">{months.map((month,i)=><button key={month} className="month-choice" aria-label={full(month)} aria-current={month===selected?'date':undefined} onClick={()=>onSelect(i)} onKeyDown={e=>{const next=e.key==='ArrowRight'?Math.min(months.length-1,i+1):e.key==='ArrowLeft'?Math.max(0,i-1):e.key==='Home'?0:e.key==='End'?months.length-1:null;if(next!==null){e.preventDefault();onSelect(next);(strip.current?.children[next] as HTMLButtonElement)?.focus({preventScroll:true});}}}>{short(month)}</button>)}</div><button className="month-arrow" aria-label="Next month" disabled={index===months.length-1} onClick={()=>onSelect(index+1)}><ChevronRight size={24}/></button></div><p className="month-strip-readout" role="status">{full(selected)}</p></section>;
}
