import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
const full=(month:string)=>new Date(month+'-01T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'});
const names=Array.from({length:12},(_,i)=>new Date(2026,i,1).toLocaleDateString('en-US',{month:'short'}));
export default function MonthNavigator({months,selected,current,onSelect,currentLabel='Current month',showEmptyMonths=false}:{months:string[];selected:string;current:string;onSelect:(index:number)=>void;currentLabel?:string;showEmptyMonths?:boolean}){
 const index=Math.max(0,months.indexOf(selected)),active=months[index]||'',years=[...new Set(months.map(month=>month.slice(0,4)))];
 const [year,setYear]=useState(active.slice(0,4));const buttons=useRef(new Map<string,HTMLButtonElement>()),focusNext=useRef(false);
 useEffect(()=>{setYear(active.slice(0,4));},[active]);
 useEffect(()=>{if(focusNext.current){const button=buttons.current.get(active);if(button){button.focus({preventScroll:true});focusNext.current=false;}}},[active,year]);
 if(!months.length)return null;
 const visibleYear=years.includes(year)?year:active.slice(0,4),yearIndex=years.indexOf(visibleYear),currentIndex=months.indexOf(current);
 function choose(next:number,focus=false){if(next<0||next>=months.length)return;setYear(months[next].slice(0,4));focusNext.current=focus;if(next===index&&focus){buttons.current.get(active)?.focus();focusNext.current=false;}else onSelect(next);}
 return <section className="month-navigator month-browser" aria-label="Browse months"><div className="month-browser-heading"><span>Browse Month</span><button type="button" className="month-browser-current" disabled={currentIndex<0} onClick={()=>choose(currentIndex)}>{currentLabel}</button></div><div className="month-browser-selection"><button type="button" className="month-browser-step" aria-label="Previous month" disabled={index===0} onClick={()=>choose(index-1)}><ChevronLeft/></button><p role="status">{full(active)}</p><button type="button" className="month-browser-step" aria-label="Next month" disabled={index===months.length-1} onClick={()=>choose(index+1)}><ChevronRight/></button></div><div className="month-browser-year"><button type="button" aria-label="Previous year" disabled={yearIndex===0} onClick={()=>setYear(years[yearIndex-1])}><ChevronLeft size={18}/></button><label><span>Year</span><select aria-label="Browse year" value={visibleYear} onChange={e=>setYear(e.target.value)}>{years.map(value=><option key={value}>{value}</option>)}</select></label><button type="button" aria-label="Next year" disabled={yearIndex===years.length-1} onClick={()=>setYear(years[yearIndex+1])}><ChevronRight size={18}/></button></div><div className="month-browser-grid" role="group" aria-label={'Months in '+visibleYear}>{names.map((name,i)=>{const month=visibleYear+'-'+String(i+1).padStart(2,'0'),position=months.indexOf(month);if(position<0&&!showEmptyMonths)return null;return <button type="button" key={month} ref={node=>{if(node)buttons.current.set(month,node);else buttons.current.delete(month);}} disabled={position<0} aria-label={full(month)} aria-current={month===active?'date':undefined} onClick={()=>choose(position)} onKeyDown={e=>{const next=e.key==='ArrowRight'?Math.min(months.length-1,position+1):e.key==='ArrowLeft'?Math.max(0,position-1):e.key==='Home'?0:e.key==='End'?months.length-1:null;if(next!==null){e.preventDefault();choose(next,true);}}}>{name}</button>;})}</div></section>;
}
