import GitHubIcon from './GitHubIcon';
import {startGitHubAuth} from './github-auth';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {supabase,assetUrl} from './static-data';
export default function OwnerLogin(){
 const dialog=useRef<HTMLDialogElement>(null);
 const [email,setEmail]=useState(''),[mode,setMode]=useState<'login'|'signup'|'legacy'|'forgot'|'recovery'>('login'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 function change(next:typeof mode){setMode(next);setError('');setMessage('');}
 useEffect(()=>{const open=()=>{setEmail('');change('login');dialog.current?.showModal();};const signup=()=>{setEmail('');change('signup');dialog.current?.showModal();};const legacy=()=>{setEmail('');change('legacy');dialog.current?.showModal();};window.addEventListener('open-owner-login',open);window.addEventListener('open-account-signup',signup);window.addEventListener('open-legacy-login',legacy);const {data:{subscription}}=supabase.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){change('recovery');dialog.current?.showModal();}setTimeout(()=>window.dispatchEvent(new Event('owner-session-change')),0);});return()=>{window.removeEventListener('open-owner-login',open);window.removeEventListener('open-account-signup',signup);window.removeEventListener('open-legacy-login',legacy);subscription.unsubscribe();};},[]);
 async function github(){setBusy(true);setError('');setMessage('');try{await startGitHubAuth();}catch(e){setError(e instanceof Error?e.message:'Could not connect to GitHub.');setBusy(false);}}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(mode==='login'||mode==='signup')return;setBusy(true);setError('');setMessage('');const form=new FormData(event.currentTarget);try{if(mode==='forgot'){const {error}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:location.origin+import.meta.env.BASE_URL});if(error)throw error;setMessage('If this legacy account exists, check your email for the password reset link.');}else if(mode==='recovery'){const password=String(form.get('password'));if(password!==form.get('confirm'))throw new Error('Passwords do not match.');const {data:{user},error:lookupError}=await supabase.auth.getUser();if(lookupError||!user)throw new Error('This reset link is no longer valid.');if(user.identities?.some(i=>i.provider==='github'))throw new Error('Your account uses GitHub. Continue with GitHub to sign in.');const {error}=await supabase.auth.updateUser({password});if(error)throw error;change('legacy');setMessage('Password updated. You can now use Legacy Sign-in.');history.replaceState(null,'',location.pathname);}else{const {data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password:String(form.get('password'))});if(error)throw new Error('Could not sign in. Check your password or use Forgot password.');if(data.user?.identities?.some(i=>i.provider==='github')){await supabase.auth.signOut({scope:'local'});change('login');throw new Error('This account is linked to GitHub. Continue with GitHub to sign in.');}window.dispatchEvent(new Event('owner-session-change'));dialog.current?.close();}}catch(e){setError(e instanceof Error?e.message:'Could not complete this request.');}finally{setBusy(false);}}
 const primary=mode==='login'||mode==='signup';
 return <dialog ref={dialog} className="owner-login-popup" aria-labelledby="owner-login-title" onCancel={e=>{if(busy)e.preventDefault();}}><form onSubmit={submit} key={mode}><div className="dialog-top"><img className="account-popup-logo" src={assetUrl('clustifle-feh-rerun-logo.png')} alt="FEH Rerun Schedule"/><button type="button" className="icon-button" aria-label="Close account sign in" disabled={busy} onClick={()=>dialog.current?.close()}><X/></button></div><h2 id="owner-login-title">{mode==='signup'?'Create an account':mode==='legacy'?'Legacy Sign-in':mode==='forgot'?'Reset legacy password':mode==='recovery'?'Choose a new password':'Account sign in'}</h2><p className="owner-login-intro">{primary?'Use GitHub to sign in or create your FEH Rerun account.':mode==='legacy'?'Existing email accounts without GitHub linked can sign in here. Link GitHub in Settings → Account to switch to GitHub sign-in.':'Password recovery is available for legacy accounts without GitHub linked.'}</p>{primary?<><button type="button" className="primary github-auth-button" disabled={busy} onClick={()=>void github()}><GitHubIcon size={20}/>{busy?'Please wait…':'Continue with GitHub'}</button><p>If you are signing in with your email, go to Legacy Sign-in.</p><button type="button" className="owner-forgot" disabled={busy} onClick={()=>change('legacy')}>Legacy Sign-in</button></>:<>{mode!=='recovery'&&<label>Email<input type="email" name="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" disabled={busy}/></label>}{mode!=='forgot'&&<label>{mode==='recovery'?'New password':'Password'}<input type="password" name="password" required minLength={mode==='recovery'?12:undefined} autoComplete={mode==='recovery'?'new-password':'current-password'} disabled={busy}/></label>}{mode==='recovery'&&<label>Confirm password<input type="password" name="confirm" required minLength={12} autoComplete="new-password" disabled={busy}/></label>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='forgot'?'Send reset link':mode==='recovery'?'Update password':'Sign in'}</button>{mode==='legacy'&&<button type="button" className="owner-forgot" disabled={busy} onClick={()=>change('forgot')}>Forgot password?</button>}<button type="button" className="owner-forgot" disabled={busy} onClick={()=>change('login')}>Back to GitHub sign-in</button></>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="import-success">{message}</p>}</form></dialog>;
}