import {useEffect,useState} from 'react';
import {supabase} from './static-data';
import ProfileHeroPicker,{type ProfileHero} from './ProfileHeroPicker';
import {HeroCollection} from './ProfileInterests';
type Saved={schedule:string;month:string};type Tracking={followed_heroes:string[];saved_schedules:Saved[]};
const options=[['General','General Schedule'],['Remix','Remix Schedule'],['Monthly Revival','Monthly Revival Schedule'],['Forging Bonds Revival','New Heroes Revival Schedule'],['Hall of Forms Revival','Hall of Forms Revival Schedule'],['Waitlist','Rerun Waitlist']];
export default function PersonalTracking({userId,heroes}:{userId:string;heroes:ProfileHero[]}){const [data,setData]=useState<Tracking>({followed_heroes:[],saved_schedules:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[picking,setPicking]=useState(false),[schedule,setSchedule]=useState('General'),[month,setMonth]=useState(()=>{const now=new Date();return now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');});useEffect(()=>{let alive=true;setLoading(true);supabase.from('tracker_personal_tracking').select('followed_heroes,saved_schedules').eq('id',userId).maybeSingle().then(({data,error})=>{if(!alive)return;if(error)setError('Could not load your private tracking. Please reopen Profile to retry.');else if(data)setData(data);setLoading(false);});return()=>{alive=false;};},[userId]);async function save(next:Tracking){if(busy||loading)return;setBusy(true);setError('');setNotice('');try{const {error}=await supabase.from('tracker_personal_tracking').upsert({id:userId,...next});if(error)throw error;setData(next);setNotice('Private tracking saved.');}catch{setError('Could not save your tracking. Please try again.');}finally{setBusy(false);}}
 return <section className="profile-private"><h3>Personal tracking <span>Only you</span></h3>{loading?<p role="status">Loading your tracking…</p>:<><h4>Followed heroes · {data.followed_heroes.length}/100</h4><p className="settings-hint">Quick access to your heroes and their latest scheduled rerun.</p><HeroCollection ids={data.followed_heroes} heroes={heroes} onRemove={busy?undefined:id=>void save({...data,followed_heroes:data.followed_heroes.filter(x=>x!==id)})}/><div className="profile-follow-dates">{data.followed_heroes.map(id=>{const h=heroes.find(x=>x.id===id);return h&&<p key={id}><strong>{h.name}</strong> · {h.month?new Date(h.month.slice(0,7)+'-01T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'}):'Next rerun not scheduled'}{h.schedule&&<span> · {options.find(([key])=>key===h.schedule)?.[1]||h.schedule}</span>}</p>;})}</div>{data.followed_heroes.length<100&&<button className="secondary" disabled={busy} onClick={()=>setPicking(true)}>Follow a hero</button>}<h4>Saved schedules · {data.saved_schedules.length}/20</h4><div className="profile-saved-list">{data.saved_schedules.map((x,i)=><div key={x.schedule+'-'+x.month}><a href={import.meta.env.BASE_URL+'?schedule='+encodeURIComponent(x.schedule)+(x.month?'&month='+x.month:'')}>{options.find(([key])=>key===x.schedule)?.[1]||'Schedule'}{x.month?' · '+new Date(x.month+'-01T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'}):''}</a><button disabled={busy} onClick={()=>void save({...data,saved_schedules:data.saved_schedules.filter((_,j)=>j!==i)})}>Remove</button></div>)}</div>{data.saved_schedules.length<20&&<form className="profile-save-schedule" onSubmit={e=>{e.preventDefault();const next={schedule,month:schedule==='Waitlist'?'':month};if(data.saved_schedules.some(x=>x.schedule===next.schedule&&x.month===next.month)){setNotice('This schedule is already saved.');return;}void save({...data,saved_schedules:[...data.saved_schedules,next]});}}><label>Schedule<select value={schedule} disabled={busy} onChange={e=>setSchedule(e.target.value)}>{options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{schedule!=='Waitlist'&&<label>Month<input required type="month" min="2025-10" max="2029-10" value={month} disabled={busy} onChange={e=>setMonth(e.target.value)}/></label>}<button className="secondary" disabled={busy}>Save schedule</button></form>}</>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="error">{error}</p>}{picking&&<ProfileHeroPicker title="Follow a hero" heroes={heroes} used={data.followed_heroes} onPick={id=>{setPicking(false);void save({...data,followed_heroes:[...data.followed_heroes,id]});}} onClose={()=>setPicking(false)}/>}</section>;
}
