import {useSyncExternalStore} from 'react';
export type Preferences={theme:'default'|'europa-nuova'|'frutiger-aero';compact:boolean;textSize:'default'|'larger';showTags:boolean;startPage:string;rememberView:boolean;rememberMonth:boolean;carouselAutoplay:boolean;carouselSeconds:number;pauseOnHover:boolean;motion:'device'|'full'|'reduced';clock:'12'|'24';timezone:'local'|'UTC';showTimezone:boolean;autoRefresh:boolean};
export const defaults:Preferences={theme:'default',compact:false,textSize:'default',showTags:true,startPage:'Homepage',rememberView:true,rememberMonth:true,carouselAutoplay:true,carouselSeconds:10,pauseOnHover:false,motion:'device',clock:'12',timezone:'local',showTimezone:false,autoRefresh:true};
export const pageOptions=[['Homepage','Home'],['General','General Schedule'],['Remix','Remix Schedule'],['Monthly Revival','Monthly Legendary/Mythic Revival Schedule'],['Forging Bonds Revival','New Heroes Revival Schedule'],['Hall of Forms Revival','Hall of Forms Revival Schedule'],['Waitlist','Rerun Waitlist'],['Profile','Profile']];
function read():Preferences{try{const raw=JSON.parse(localStorage.getItem('feh-preferences')||'{}');const next={...defaults};for(const key of Object.keys(defaults) as (keyof Preferences)[]){if(typeof raw[key]===typeof defaults[key])(next as Record<string,unknown>)[key]=raw[key];}if(!localStorage.getItem('feh-preferences'))next.compact=localStorage.getItem('feh-compact')==='true';if(!pageOptions.some(([key])=>key===next.startPage))next.startPage='Homepage';if(![5,10,15,20].includes(next.carouselSeconds))next.carouselSeconds=10;for(const [key,options] of Object.entries({theme:['default','europa-nuova','frutiger-aero'],textSize:['default','larger'],motion:['device','full','reduced'],clock:['12','24'],timezone:['local','UTC']}))if(!options.includes(String((next as Record<string,unknown>)[key])))(next as Record<string,unknown>)[key]=(defaults as Record<string,unknown>)[key];return next;}catch{return {...defaults};}}
let preferences=read();const listeners=new Set<()=>void>();
function apply(){const root=document.documentElement;root.dataset.theme=preferences.theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',preferences.theme==='europa-nuova'?'#17100c':preferences.theme==='frutiger-aero'?'#167ec1':'#234b59');root.dataset.textSize=preferences.textSize;root.dataset.heroTags=preferences.showTags?'show':'hide';root.dataset.motion=reduceMotion()?'reduced':'full';}
export function reduceMotion(){return preferences.motion==='reduced'||(preferences.motion==='device'&&window.matchMedia('(prefers-reduced-motion: reduce)').matches);}
function changed(){apply();listeners.forEach(fn=>fn());window.dispatchEvent(new Event('preferences-change'));}
export function getPreferences(){return preferences;}
export function setPreferences(patch:Partial<Preferences>){preferences={...preferences,...patch};try{localStorage.setItem('feh-preferences',JSON.stringify(preferences));localStorage.setItem('feh-compact',String(preferences.compact));}catch{}changed();}
export function resetPreferences(){setPreferences({...defaults});try{for(const key of ['feh-current-view','feh-current-month','feh-last-view','feh-last-month','feh-revival-month-forging_bonds_revivals','feh-revival-month-hall_of_forms_revivals']){localStorage.removeItem(key);sessionStorage.removeItem(key);}}catch{}}
export function usePreferences(){return useSyncExternalStore(fn=>{listeners.add(fn);return()=>{listeners.delete(fn);};},getPreferences);}
window.addEventListener('storage',event=>{if(event.key==='feh-preferences'){preferences=read();changed();}});
window.matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',apply);apply();
export function recordUpdate(){try{sessionStorage.setItem('feh-last-update',String(Date.now()));}catch{}window.dispatchEvent(new Event('data-updated'));}
