import {useEffect,useRef,useState} from 'react';
import {UserRound,Upload,Plus,Link as LinkIcon} from 'lucide-react';
import {supabase} from './static-data';
import ProfileInterests,{HeroCollection,defaultInterests,type Interests} from './ProfileInterests';
import PersonalTracking from './PersonalTracking';
import type {ProfileHero} from './ProfileHeroPicker';
type Social={label:string;url:string};type ProfileData={id:string;display_name:string;bio:string;avatar_path:string|null;social_links:Social[];username?:string|null;about?:string;favorite_heroes?:string[];favorite_games?:string[];visibility?:Record<string,boolean>;role?:string|null};
const headAdministratorId='360457b7-e43f-4bf7-bcb1-d9792233a243';
function safeUrl(value:string){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null;}catch{return null;}}
export default function Profile({editor=false}:{editor?:boolean}){
 const [interests,setInterests]=useState<Interests>(defaultInterests),[heroes,setHeroes]=useState<ProfileHero[]>([]),[heroError,setHeroError]=useState('');
 useEffect(()=>{let alive=true;supabase.from('heroes').select('id,name,title,color,portrait,schedule,month').order('name').then(({data,error})=>{if(!alive)return;if(error)setHeroError('Could not load hero portraits. Reload to try again.');else setHeroes(data||[]);});return()=>{alive=false;};},[]);
 const [profile,setProfile]=useState<ProfileData|null>(null),[userId,setUserId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[name,setName]=useState(''),[bio,setBio]=useState(''),[links,setLinks]=useState<Social[]>([]),[picture,setPicture]=useState<File|null>(null),[preview,setPreview]=useState(''),[removeAvatar,setRemoveAvatar]=useState(false);const file=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setError('');try{const {data:{session},error:authError}=await supabase.auth.getSession();if(authError)throw authError;const own=session?.user.id||'';setUserId(own);const target=editor?own:new URLSearchParams(location.search).get('profile')||own;if(!target){setProfile(null);return;}const {data,error}=editor?await supabase.from('tracker_profiles').select('*').eq('id',target).maybeSingle():await supabase.rpc('get_public_tracker_profile',{profile_id:target});if(error)throw error;const source=data as ProfileData|null;const row=source?{...source,social_links:Array.isArray(source.social_links)?source.social_links.filter(x=>x&&typeof x.url==='string'&&safeUrl(x.url)).map(x=>({label:typeof x.label==='string'?x.label:'',url:x.url})):[]}:null;setProfile(row);setName(row?.display_name||'');setBio(row?.bio||'');setLinks(Array.isArray(row?.social_links)?row.social_links:[]);setInterests({username:row?.username||'',about:row?.about||'',favorite_heroes:row?.favorite_heroes||[],favorite_games:row?.favorite_games||[],visibility:{...defaultInterests.visibility,...row?.visibility}});}catch{setError('Could not load this profile. Please try again.');}finally{setLoading(false);}}
 useEffect(()=>{void load();const update=()=>void load();window.addEventListener('owner-session-change',update);window.addEventListener('profile-updated',update);return()=>{window.removeEventListener('owner-session-change',update);window.removeEventListener('profile-updated',update);};},[editor]);
 useEffect(()=>{if(!picture){setPreview('');return;}const url=URL.createObjectURL(picture);setPreview(url);return()=>URL.revokeObjectURL(url);},[picture]);
 function choosePicture(f:File){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2097152){setError('Choose a PNG, JPG or WebP picture under 2 MB.');return;}setPicture(f);setRemoveAvatar(false);setError('');}
 async function save(e:React.FormEvent){e.preventDefault();if(!userId||saving)return;setSaving(true);setError('');setNotice('');let uploaded:string|null=null;try{if(!name.trim())throw new Error('Enter a display name.');const cleanLinks=links.filter(x=>x.url.trim()).map(x=>{const url=safeUrl(x.url.trim());if(!url)throw new Error('Social links must be valid HTTP or HTTPS addresses.');return {label:x.label.trim().slice(0,40)||new URL(url).hostname,url};});let path=removeAvatar?null:profile?.avatar_path||null;if(picture){const ext=picture.type==='image/png'?'png':picture.type==='image/webp'?'webp':'jpg';uploaded=userId+'/'+(typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join(''))+'.'+ext;const {error}=await supabase.storage.from('profile-avatars').upload(uploaded,picture,{contentType:picture.type});if(error)throw error;path=uploaded;}const row={id:userId,...interests,username:interests.username.trim()||null,display_name:name.trim(),bio:bio.trim(),avatar_path:path,social_links:cleanLinks,updated_at:new Date().toISOString()};const {error}=await supabase.from('tracker_profiles').upsert(row);if(error)throw new Error(error.code==='23505'?'That username is already taken. Choose another.':error.message);const old=profile?.avatar_path;setProfile(row);setPicture(null);setRemoveAvatar(false);if(old&&old!==path)await supabase.storage.from('profile-avatars').remove([old]);setNotice('Profile saved. Your public visibility choices are applied.');window.dispatchEvent(new Event('profile-updated'));}catch(e){if(uploaded)await supabase.storage.from('profile-avatars').remove([uploaded]);setError(e instanceof Error?e.message:'Could not save your profile.');}finally{setSaving(false);}}
 const avatar=preview||(!removeAvatar&&profile?.avatar_path?supabase.storage.from('profile-avatars').getPublicUrl(profile.avatar_path).data.publicUrl:'');const share=profile?new URL('?profile='+profile.id,location.origin+import.meta.env.BASE_URL).href:'';
 if(loading)return <p role="status">Loading profile…</p>;
 if(editor&&!userId)return <div className="profile-empty"><p>Sign in to customize your profile.</p><button className="primary" onClick={()=>window.dispatchEvent(new Event('open-owner-login'))}>Sign in</button></div>;
 if(editor)return <form className="profile-editor" onSubmit={save}><p className="settings-hint">Your name and picture are public. Choose which optional details to show below.</p><div className="profile-avatar-identity"><div className="profile-picture">{avatar?<img src={avatar} alt="Profile picture preview"/>:<UserRound size={48}/>}</div>{userId===headAdministratorId&&<span className="profile-admin-tag">Head Administrator</span>}</div><div className="profile-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>file.current?.click()}><Upload size={16}/>Change picture</button>{avatar&&<button type="button" className="secondary" disabled={saving} onClick={()=>{setPicture(null);setRemoveAvatar(true);}}>Remove picture</button>}</div><input hidden ref={file} type="file" accept="image/png,image/jpeg,image/webp" disabled={saving} onChange={e=>{const f=e.target.files?.[0];if(f)choosePicture(f);e.target.value='';}}/><small>PNG, JPG or WebP · up to 2 MB</small><label>Display name<input required maxLength={80} value={name} disabled={saving} onChange={e=>setName(e.target.value)}/></label><label>Bio<textarea rows={4} maxLength={1000} value={bio} disabled={saving} onChange={e=>setBio(e.target.value)}/></label><h4>Social links</h4>{links.map((link,i)=><div className="profile-link-row" key={i}><input aria-label={'Link '+(i+1)+' label'} placeholder="Reddit, YouTube…" maxLength={40} value={link.label} disabled={saving} onChange={e=>setLinks(old=>old.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/><input aria-label={'Link '+(i+1)+' address'} placeholder="https://…" type="url" maxLength={500} value={link.url} disabled={saving} onChange={e=>setLinks(old=>old.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/><button type="button" aria-label={'Remove link '+(i+1)} disabled={saving} onClick={()=>setLinks(old=>old.filter((_,j)=>j!==i))}>Remove</button></div>)}{links.length<6&&<button type="button" className="secondary" disabled={saving} onClick={()=>setLinks(old=>[...old,{label:'',url:''}])}><Plus size={16}/>Add social link</button>}<ProfileInterests value={interests} onChange={setInterests} heroes={heroes} disabled={saving}/>{heroError&&<p role="alert">{heroError}</p>}<div className="profile-actions"><button className="primary" disabled={saving}>{saving?'Saving…':'Save profile'}</button>{share&&<a href={share}>View public profile</a>}</div>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="error">{error}</p>}</form>;
 return <section className="public-profile"><p className="profile-eyebrow">Profile</p>{error?<p className="error" role="alert">{error} <button onClick={()=>void load()}>Try again</button></p>:profile?<><div className="profile-avatar-identity"><div className="profile-picture">{avatar?<img src={avatar} alt={profile.display_name+' profile picture'}/>:<UserRound size={56}/>}</div>{(profile.role||profile.id===headAdministratorId)&&<span className="profile-admin-tag">{profile.role||'Head Administrator'}</span>}</div><h2>{profile.display_name||'FEH fan'}</h2>{profile.username&&<p className="profile-username">@{profile.username}</p>}{profile.bio&&<p className="profile-bio">{profile.bio}</p>}{profile.about&&<section className="profile-about"><h3>About me</h3><p>{profile.about}</p></section>}{!!profile.favorite_heroes?.length&&<section className="profile-favorites"><h3>Favorite heroes</h3><HeroCollection ids={profile.favorite_heroes} heroes={heroes}/></section>}{!!profile.favorite_games?.length&&<section className="profile-games"><h3>Favorite Fire Emblem titles</h3><div className="profile-game-list">{profile.favorite_games.map(x=><span key={x}>{x}</span>)}</div></section>}<div className="profile-socials">{profile.social_links.filter(x=>safeUrl(x.url)).map((x,i)=><a key={i} href={safeUrl(x.url)!} target="_blank" rel="noopener noreferrer"><LinkIcon size={16}/>{x.label||new URL(x.url).hostname}</a>)}</div><div className="profile-actions"><button className="secondary" onClick={()=>{void navigator.clipboard.writeText(share).then(()=>setNotice('Profile link copied.')).catch(()=>setNotice('Copy this profile URL from your address bar.'));}}>Copy profile link</button>{profile.id===userId&&<button className="secondary" onClick={()=>window.dispatchEvent(new Event('edit-profile'))}>Edit profile</button>}</div>{notice&&<p role="status">{notice}</p>}{profile.id===userId&&<PersonalTracking userId={userId} heroes={heroes}/>}</>:<div className="profile-empty"><h2>{userId?'Create your profile':new URLSearchParams(location.search).has('profile')?'Profile unavailable':'Your profile'}</h2><p>{userId?'Add your name, picture and bio in Settings → Account.':'Sign in to create a profile, or open a shared profile link.'}</p><button className="primary" onClick={()=>window.dispatchEvent(new Event(userId?'edit-profile':'open-owner-login'))}>{userId?'Customize profile':'Sign in'}</button></div>}</section>;
}
