import HeroPortraitMarks from './HeroPortraitMarks';
import {useEffect,useRef,useState} from 'react';
import {Search,X,Check} from 'lucide-react';
import {portraitUrl} from './static-data';
import './ProfileHeroPicker.css';
export type ProfileHero={id:string;name:string;title:string;color:string;heroic_grail?:boolean;category?:string;blessing?:string|null;weapon_type?:string|null;move_type?:string|null;portrait:string|null;schedule:string;month:string|null};
export default function ProfileHeroPicker({title,heroes,used,onPick,onPickMany,onClose,onAdd}:{title:string;heroes:ProfileHero[];used:string[];onPick:(id:string)=>void;onPickMany?:(ids:string[])=>Promise<void>;onClose:()=>void;onAdd?:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[query,setQuery]=useState(''),[color,setColor]=useState('All'),[selected,setSelected]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog.current?.close();document.body.style.overflow=before;};},[]);
 const filtered=heroes.filter(h=>(color==='All'||color===h.color)&&`${h.name} ${h.title}`.toLowerCase().includes(query.trim().toLowerCase())),available=filtered.filter(h=>!used.includes(h.id));
 function close(){if(!busy)onClose();}
 async function submit(){if(!onPickMany||!selected.size)return;setBusy(true);setError('');try{await onPickMany([...selected].filter(id=>!used.includes(id)));onClose();}catch(e){setError(e instanceof Error?e.message:'Could not add the selected heroes. Try again.');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="revival-hero-picker" aria-label={title} onCancel={e=>{e.preventDefault();close();}}><header className="revival-picker-header"><h2>{title}</h2><button type="button" className="icon-button" aria-label="Close hero selection" disabled={busy} onClick={close}><X/></button></header><div className="revival-picker-tools"><label className="revival-picker-search"><Search size={20}/><input autoFocus aria-label="Search profile heroes" type="search" placeholder="Search hero name or title…" value={query} disabled={busy} onChange={e=>setQuery(e.target.value)}/></label><div className="revival-picker-colors">{['All','Red','Blue','Green','Colorless'].map(c=><button type="button" key={c} aria-pressed={color===c} disabled={busy} onClick={()=>setColor(c)}>{c==='All'?'All colors':c}</button>)}</div>{onPickMany&&<div className="picker-multi-actions"><button className="secondary" disabled={busy||!available.length} onClick={()=>setSelected(old=>new Set([...old,...available.map(h=>h.id)]))}>Select matching</button><button className="secondary" disabled={busy||!selected.size} onClick={()=>setSelected(new Set())}>Clear selection</button><span role="status">{selected.size} selected</span></div>}</div><div className="revival-picker-grid">{filtered.map(h=><button type="button" key={h.id} className={'revival-picker-card '+h.color.toLowerCase()+(selected.has(h.id)?' is-multi-selected':'')} role={onPickMany?'checkbox':undefined} aria-checked={onPickMany?selected.has(h.id):undefined} disabled={busy||used.includes(h.id)} onClick={()=>{if(onPickMany)setSelected(old=>{const next=new Set(old);next.has(h.id)?next.delete(h.id):next.add(h.id);return next;});else onPick(h.id);}}>{onPickMany&&<span className="picker-selection-mark" aria-hidden="true">{selected.has(h.id)&&<Check size={18}/>}</span>}<span className="revival-picker-portrait">{h.portrait?<img src={portraitUrl(h.portrait)} alt={h.name+' portrait'} loading="lazy" decoding="async"/>:h.name[0]}<HeroPortraitMarks hero={h}/></span><strong>{h.name}</strong><span className="revival-picker-subtitle">{h.title}</span><small>{used.includes(h.id)?'Already in this list':h.color}</small></button>)}{!filtered.length&&<p>No heroes match your search.</p>}</div>{error&&<p className="error picker-multi-error" role="alert">{error}</p>}<footer className="revival-picker-footer">{onAdd&&<button type="button" className="secondary" disabled={busy} onClick={onAdd}>Add new Hero</button>}<span>{onPickMany?'Selection stays when you search or change colors.':'Select a hero portrait.'}</span><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button>{onPickMany&&<button className="primary" disabled={busy||!selected.size||selected.size>500} onClick={()=>void submit()}>{busy?'Adding…':'Add selected ('+selected.size+')'}</button>}</footer></dialog>;
}
