import HeroPortraitMarks from './HeroPortraitMarks';
import {useEffect,useRef,useState} from 'react';
import {Check,Search,X} from 'lucide-react';
import {portraitUrl} from './static-data';
type Hero={id:string;name:string;title:string;color:string;category?:string;blessing?:string|null;weapon_type?:string|null;move_type?:string|null;portrait?:string|null};
export default function RevivalHeroPicker({open,slot,heroes,selected,used,onPick,onClose,title="Choose a hero",context,footer,requiredColor}:{title?:string;context?:string;footer?:string;requiredColor?:string;open:boolean;slot:number;heroes:Hero[];selected:string|null;used:string[];onPick:(id:string|null)=>void;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),searchInput=useRef<HTMLInputElement>(null),grid=useRef<HTMLDivElement>(null);
 const [search,setSearch]=useState(''),[color,setColor]=useState('All');
 useEffect(()=>{const modal=dialog.current;if(!modal)return;if(!open){modal.close();return;}setSearch('');setColor('All');modal.showModal();if(grid.current)grid.current.scrollTop=0;searchInput.current?.focus();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;modal.close();};},[open]);
 const filtered=heroes.filter(hero=>(!requiredColor||hero.color===requiredColor)&&(color==='All'||hero.color===color)&&`${hero.name} ${hero.title}`.toLowerCase().includes(search.trim().toLowerCase()));
 return <dialog ref={dialog} className="revival-hero-picker" aria-labelledby="revival-picker-title" onCancel={e=>{e.preventDefault();onClose();}}><header className="revival-picker-header"><div><p>{context||`New Heroes Revival · Hero ${slot}`}</p><h2 id="revival-picker-title">{title}</h2></div><button type="button" className="icon-button" aria-label="Close hero picker" onClick={onClose}><X/></button></header><div className="revival-picker-tools"><label className="revival-picker-search"><Search size={20}/><input ref={searchInput} type="search" aria-label="Search heroes" placeholder="Search hero name or title…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="revival-picker-colors" aria-label="Filter by weapon color" hidden={!!requiredColor}>{['All','Red','Blue','Green','Colorless'].map(value=><button type="button" key={value} aria-pressed={color===value} onClick={()=>setColor(value)}>{value==='All'?'All colors':value}</button>)}</div><div className="revival-picker-summary"><span role="status">{filtered.length} {filtered.length===1?'hero':'heroes'}</span><button type="button" onClick={()=>onPick(null)}>Leave slot empty</button></div></div><div className="revival-picker-grid" ref={grid}>{filtered.map(hero=>{const active=selected===hero.id,unavailable=used.includes(hero.id);return <button type="button" key={hero.id} className={'revival-picker-card '+hero.color.toLowerCase()+(active?' is-selected':'')} aria-label={hero.name+' · '+hero.title+' · '+hero.color+(unavailable?' · Already in lineup':'')} aria-pressed={active} disabled={unavailable} onClick={()=>onPick(hero.id)}><span className="revival-picker-portrait">{hero.portrait?<img src={portraitUrl(hero.portrait)} alt={hero.name+' portrait'} loading="lazy" decoding="async"/>:<span>{hero.name.slice(0,1)}</span>}<HeroPortraitMarks hero={hero}/>{active&&<span className="revival-picker-check"><Check size={18}/></span>}</span><strong>{hero.name}</strong><span className="revival-picker-subtitle">{hero.title}</span><small>{unavailable?'Already in lineup':hero.color}</small></button>;})}{!filtered.length&&<p className="revival-picker-empty">No heroes match your search. Try another name or color.</p>}</div><footer className="revival-picker-footer"><span>{footer||"Select a portrait to fill this slot. Save revival to publish your lineup."}</span><button type="button" className="secondary" onClick={onClose}>{context?"Back to banner":"Back to Edit Revival"}</button></footer></dialog>;
}
