import {useEffect,useRef,useState} from 'react';
import {UserRound,X} from 'lucide-react';
import {supabase} from './static-data';
export default function Settings(){
 const dialog=useRef<HTMLDialogElement>(null);
 const [email,setEmail]=useState(''),[role,setRole]=useState<string|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setLoading(true);setError('');try{const {data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;const {data:{user},error}=session?await supabase.auth.getUser():{data:{user:null},error:null};if(error)throw error;setEmail(user?.email||'');if(user){const {data,error}=await supabase.rpc('tracker_role');if(error)throw error;setRole(data);}else setRole(null);}catch{setError('Could not load account settings. Please try again.');}finally{setLoading(false);}}
 useEffect(()=>{const open=()=>{dialog.current?.showModal();void refresh();};const update=()=>{if(dialog.current?.open)void refresh();};window.addEventListener('open-settings',open);window.addEventListener('owner-session-change',update);return()=>{window.removeEventListener('open-settings',open);window.removeEventListener('owner-session-change',update);};},[]);
 function action(name:string){window.dispatchEvent(new Event(name));}
 async function signOut(){setBusy(true);setError('');const {error}=await supabase.auth.signOut();if(error)setError('Could not sign out. Please try again.');else{window.dispatchEvent(new Event('owner-session-change'));await refresh();}setBusy(false);}
 return <dialog ref={dialog} className="settings-page" aria-labelledby="settings-title"><header className="settings-header"><div><h2 id="settings-title">Settings</h2><p>Your account and access to the schedule.</p></div><button className="icon-button" aria-label="Close settings" disabled={busy} onClick={()=>dialog.current?.close()}><X/></button></header><main className="settings-body"><section className="settings-account"><div className="settings-section-title"><UserRound/><h3>Account</h3></div>{loading?<p role="status">Loading account…</p>:email?<><p className="settings-email">{email}</p><span className="settings-role">{role==='Owner'?'Head Administrator':role==='Manager'?'Schedule Manager':'Visitor'}</span><p>{role==='Owner'?'Manage your session and Schedule Manager access.':role==='Manager'?'You can edit heroes, banners, and revival schedules.':'Your account is signed in. Schedule editing is reserved for authorized editors.'}</p><div className="settings-actions">{role==='Owner'&&<button className="primary" onClick={()=>action('open-managers')}>Manage Schedule Managers</button>}<button className="secondary" onClick={()=>action('open-owner-login')}>Password & sign-in help</button><button className="secondary" disabled={busy} onClick={()=>void signOut()}>Sign out</button></div></>:<><p>Sign in or create an account with your email.</p><div className="settings-actions"><button className="primary" onClick={()=>action('open-owner-login')}>Sign in</button><button className="secondary" onClick={()=>action('open-account-signup')}>Create account</button></div><p className="settings-access-note">New accounts have visitor access. Only the Head Administrator can grant Schedule Manager access.</p></>}{error&&<p role="alert" className="error">{error} <button onClick={()=>void refresh()}>Try again</button></p>}</section></main></dialog>;
}
