import About from './About';
import {readRoute,goTo,settingsUrl} from './routes';
import {useEffect,useRef,useState} from 'react';
import {ChevronRight,ChevronLeft} from 'lucide-react';
import {usePreferences,setPreferences,resetPreferences,reduceMotion,pageOptions,type Preferences} from './preferences';
import Profile from './Profile';
import {supabase} from './static-data';
export default function Settings({onClose,signedIn}:{onClose:()=>void;signedIn:boolean}){
 const [closing,setClosing]=useState(false);const closeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);function closeSettings(){if(closing)return;setClosing(true);closeTimer.current=setTimeout(()=>{onClose();setClosing(false);},reduceMotion()?0:220);}useEffect(()=>()=>{if(closeTimer.current)clearTimeout(closeTimer.current);},[]);
 const [mobileCategoryOpen,setMobileCategoryOpen]=useState(()=>Boolean(readRoute().section));
 const sections=[...(signedIn?['Account']:[]),'Personalization','Date & time','Updates','About','Reset'];
 const preferences=usePreferences();const [section,setSection]=useState(signedIn?'Account':'Personalization');const [notice,setNotice]=useState(''),[resetOpen,setResetOpen]=useState(false),[lastUpdate,setLastUpdate]=useState(()=>{try{return Number(sessionStorage.getItem('feh-last-update'))||0;}catch{return 0;}});
 useEffect(()=>{const sync=()=>{const rawSection=readRoute().section;setMobileCategoryOpen(Boolean(rawSection));const requested=['appearance','navigation','home-carousel','motion'].includes(rawSection)?'personalization':rawSection;setSection(sections.find(name=>settingsUrl(name).split('/').pop()===requested)||(signedIn?'Account':'Personalization'));};sync();window.addEventListener('route-change',sync);window.addEventListener('popstate',sync);return()=>{window.removeEventListener('route-change',sync);window.removeEventListener('popstate',sync);};},[signedIn]);
 function chooseSection(name:string){setMobileCategoryOpen(true);setSection(name);goTo(settingsUrl(name));}
 useEffect(()=>{const update=()=>{try{setLastUpdate(Number(sessionStorage.getItem('feh-last-update'))||0);}catch{}};window.addEventListener('data-updated',update);return()=>window.removeEventListener('data-updated',update);},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(timer);},[notice]);
 function change(patch:Partial<Preferences>){setPreferences(patch);setNotice('Preference updated');}
 function check(key:keyof Preferences,title:string,description:string){return <label className="settings-row"><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={!!preferences[key]} onChange={e=>change({[key]:e.target.checked})}/></label>;}
 function select(key:keyof Preferences,title:string,description:string,options:[string,string][]){return <label className="settings-row"><span><strong>{title}</strong><small>{description}</small></span><select value={String(preferences[key])} onChange={e=>change({[key]:key==='carouselSeconds'?Number(e.target.value):e.target.value})}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>;}
 const dialog=useRef<HTMLDialogElement>(null),bodyOverflow=useRef<string|null>(null);
 useEffect(()=>{const release=()=>{if(bodyOverflow.current!==null){document.body.style.overflow=bodyOverflow.current;bodyOverflow.current=null;}};const node=dialog.current;node?.addEventListener('close',release);return()=>{node?.removeEventListener('close',release);release();};},[]);
 const [email,setEmail]=useState(''),[role,setRole]=useState<string|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setLoading(true);setError('');try{const {data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;const {data:{user},error}=session?await supabase.auth.getUser():{data:{user:null},error:null};if(error)throw error;setEmail(user?.email||'');if(user){const {data,error}=await supabase.rpc('tracker_role');if(error)throw error;setRole(data);}else setRole(null);}catch{setError('Could not load account settings. Please try again.');}finally{setLoading(false);}}
 useEffect(()=>{const open=()=>{if(closeTimer.current)clearTimeout(closeTimer.current);setClosing(false);if(bodyOverflow.current===null)bodyOverflow.current=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.showModal();void refresh();};const update=()=>{void refresh();};void refresh();window.addEventListener('owner-session-change',update);return()=>{window.removeEventListener('open-settings',open);window.removeEventListener('owner-session-change',update);};},[]);
 function action(name:string){window.dispatchEvent(new Event(name));}
 async function signOut(){setBusy(true);setError('');const {error}=await supabase.auth.signOut();if(error)setError('Could not sign out. Please try again.');else{window.dispatchEvent(new Event('owner-session-change'));await refresh();}setBusy(false);}
 return <section className={"settings-inline"+(mobileCategoryOpen?" mobile-category-open":"")+(closing?" is-closing":"")} aria-labelledby="settings-title"><header className="settings-header"><div><h2 id="settings-title">Settings</h2><p>Make the schedule comfortable for you.</p></div></header><div className="settings-layout"><div className="settings-mobile-categories" aria-label="Settings categories">{sections.map(name=><button key={name} onClick={()=>chooseSection(name)}><span>{name}</span><ChevronRight size={18}/></button>)}</div><button className="settings-category-back" onClick={()=>{setMobileCategoryOpen(false);goTo(settingsUrl());}}><ChevronLeft size={18}/>All categories</button><nav className="settings-sections" aria-label="Settings sections">{sections.map(name=><button key={name} aria-current={section===name?'location':undefined} onClick={()=>chooseSection(name)}>{name}</button>)}</nav><main className="settings-body" data-section={section} key={section}>{signedIn&&<section id="settings-Account" className="settings-account"><div className="settings-section-title"><h3>Account</h3></div>{loading?<p role="status">Loading accountâ€¦</p>:email?<><p className="settings-email">{email}</p><p className="account-email-note">Your sign-in email is private.</p><span className="settings-role">{role==='Owner'?'Head Administrator':role==='Manager'?'Schedule Manager':'Visitor'}</span><p>{role==='Owner'?'Customize your public profile and manage Schedule Manager access.':role==='Manager'?'Customize your public profile and edit heroes, banners, and revival schedules.':'Customize your public profile below. Schedule editing is reserved for authorized editors.'}</p><div className="settings-actions">{role==='Owner'&&<button className="primary" onClick={()=>action('open-managers')}>Assign roles</button>}<button className="secondary" onClick={()=>action('open-owner-login')}>Password & sign-in help</button><button className="secondary" disabled={busy} onClick={()=>void signOut()}>Sign out</button></div></>:<><p>Sign in or create an account with your email.</p><div className="settings-actions"><button className="primary" onClick={()=>action('open-owner-login')}>Sign in</button><button className="secondary" onClick={()=>action('open-account-signup')}>Create account</button></div><p className="settings-access-note">New accounts have visitor access. Only the Head Administrator can grant Schedule Manager access.</p></>}{email&&<Profile editor/>}{error&&<p role="alert" className="error">{error} <button onClick={()=>void refresh()}>Try again</button></p>}</section>}
<section id="settings-Personalization" className="settings-personalization"><h3>Personalization</h3><section id="settings-Appearance" className="settings-group"><h3>Appearance</h3><fieldset className="theme-picker"><legend>Theme</legend><p className="settings-hint">Personalize the entire site. Your choice is saved on this device.</p><div className="theme-options">{([['default','Default','The original teal appearance.'],['europa-nuova','Energy Wave','Bold typography, orange accents, and a graphic wave background.'],['frutiger-aero','Frutiger Aero','Segoe UI, reflective Aero glass, and a luminous sky background.']] as const).map(([value,label,description])=><label key={value} className={'theme-option theme-option-'+value+(preferences.theme===value?' is-selected':'')}><input type="radio" name="appearance-theme" value={value} checked={preferences.theme===value} onChange={()=>change({theme:value})}/><span className="theme-preview" aria-hidden="true"><span className="theme-preview-heading">Aa</span><span className="theme-preview-lines"><i/><i/></span><span className="theme-preview-accent"/></span><span className="theme-option-copy"><strong>{label}</strong><small>{description}</small></span></label>)}</div></fieldset>{check('compact','Compact view by default','Applies immediately to schedules that support Compact view.')}{select('textSize','Text size','Increase schedule names, labels, and controls.',[['default','Default'],['larger','Larger']])}{check('showTags','Show portrait tags','Display hero type tags beneath portraits. Details remain available.')}</section>
<section id="settings-Navigation" className="settings-group"><h3>Navigation</h3>{select('startPage','Start page','Used on your next visit when remembering the last schedule is off.',pageOptions as [string,string][])}{check('rememberView','Remember last schedule','Open the schedule you last visited on this device.')}{check('rememberMonth','Remember selected month','Resume your last browsed month; otherwise start at the current month.')}</section>
<section id="settings-Home carousel" className="settings-group"><h3>Home carousel</h3>{check('carouselAutoplay','Auto-play','Automatically advance through current banners.')}{select('carouselSeconds','Time per banner','The filling navigation indicator follows this duration.',[['5','5 seconds'],['10','10 seconds'],['15','15 seconds'],['20','20 seconds']])}{check('pauseOnHover','Pause while hovering','Pause the countdown while a mouse is over the banner.')}</section>
<section id="settings-Motion" className="settings-group"><h3>Motion</h3>{select('motion','Animation preference','Reduced motion removes decorative animations and smooth transitions.',[['device','Follow device'],['full','Full animations'],['reduced','Reduced animations']])}</section>
</section><section id="settings-Date & time" className="settings-group"><h3>Date & time</h3>{select('clock','Clock format','Applies to active banner dates.',[['12','12-hour'],['24','24-hour']])}{select('timezone','Timezone','Display banner times locally or in UTC. Event dates are unchanged.',[['local','Local time'],['UTC','UTC']])}{check('showTimezone','Show timezone','Include the timezone abbreviation next to banner dates.')}<p className="settings-hint">Your local timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p></section>
<section id="settings-Updates" className="settings-group"><h3>Updates</h3>{check('autoRefresh','Auto-refresh','Check for new schedule data every 30 seconds while the page is visible. Editing forms pause updates.')}<p className="settings-hint" role="status">{lastUpdate?'Last successful data update: '+new Date(lastUpdate).toLocaleString():'No successful data update this session yet.'}</p><button className="secondary" onClick={()=>{window.dispatchEvent(new Event('refresh-now'));setNotice(navigator.onLine?'Checking for updatesâ€¦':'You are offline. Reconnect to refresh.');}}>Refresh now</button></section>
<About/><section id="settings-Reset" className="settings-group"><h3>Reset</h3><p>Restore this deviceâ€™s preferences. Your account and saved schedule data stay intact.</p>{resetOpen?<div className="settings-actions"><span>Restore default settings?</span><button className="primary" onClick={()=>{resetPreferences();setResetOpen(false);setNotice('Default settings restored');}}>Restore defaults</button><button className="secondary" onClick={()=>setResetOpen(false)}>Cancel</button></div>:<button className="secondary" onClick={()=>setResetOpen(true)}>Reset settings</button>}</section>
</main></div><p className="settings-notice" role="status">{notice}</p></section>;
}
