import {useRef,useState} from 'react';
import {Search,UserRound,ChevronRight} from 'lucide-react';
import {supabase} from './static-data';
import {goTo,viewUrl} from './routes';
type PublicUser={id:string;username:string;display_name:string;avatar_path:string|null};
export default function Users(){
 const [query,setQuery]=useState(''),[searched,setSearched]=useState(''),[results,setResults]=useState<PublicUser[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false);const request=useRef(0);
 async function search(term:string,page=0){const clean=term.trim().replace(/^@/,'');if(clean.length<2||clean.length>80)return;const token=++request.current;setBusy(true);setError('');setResults([]);setMore(false);setSearched(clean);try{const {data,error}=await supabase.rpc('search_public_tracker_profiles',{search_term:clean,result_offset:page});if(error)throw error;if(token!==request.current)return;const rows=(data||[]) as PublicUser[];setResults(rows.slice(0,20));setMore(rows.length>20&&page<500);setOffset(page);}catch{if(token===request.current){setResults([]);setError('Could not search users. Please try again.');}}finally{if(token===request.current)setBusy(false);}}
 return <section className="user-directory"><header><p className="profile-eyebrow">Community</p><h2>Find Users</h2><p>Find a public profile by username or display name.</p></header><form className="user-search" onSubmit={e=>{e.preventDefault();void search(query);}}><label><Search size={20}/><input aria-label="Search users" type="search" placeholder="Username or display name" value={query} maxLength={80} onChange={e=>setQuery(e.target.value)}/></label><button className="primary" disabled={busy||query.trim().replace(/^@/,'').length<2}>{busy?'Searching…':'Search'}</button></form><p className="settings-hint">Enter at least two characters. Only public profile information appears here.</p><div aria-live="polite">{error?<p className="error" role="alert">{error} <button onClick={()=>void search(searched,offset)}>Try again</button></p>:searched&&!busy&&<p className="user-search-count">{results.length?`Results for “${searched}”`:'No users found. Try another name.'}</p>}</div><div className="user-search-results">{results.map(user=><a className="user-search-result" key={user.id} href={viewUrl('Profile','',user.username||user.id)} onClick={e=>{if(e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();goTo(viewUrl('Profile','',user.username||user.id));}}}><span className="user-search-avatar">{user.avatar_path?<img src={supabase.storage.from('profile-avatars').getPublicUrl(user.avatar_path).data.publicUrl} alt="" loading="lazy"/>:<UserRound/>}</span><span><strong>{user.display_name||user.username}</strong><small>@{user.username}</small></span><ChevronRight size={20}/></a>)}</div>{!error&&searched&&<div className="user-search-pages">{offset>0&&<button className="secondary" disabled={busy} onClick={()=>void search(searched,Math.max(0,offset-20))}>Previous</button>}{more&&<button className="secondary" disabled={busy} onClick={()=>void search(searched,offset+20)}>Next</button>}</div>}</section>;
}
