import VersionsManagement from './VersionsManagement';
import BulkEditor from './BulkEditor';
import {Grid2X2,List,LayoutGrid,Shield} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {betaRequest} from './beta';
import {assetUrl,portraitUrl,apiFetch} from './static-data';
import {useVersions,loadVersions} from './VersionSelect';
import VersionSelect from './VersionSelect';
import {weaponTypes,allWeaponTypes} from './weapon-types';
import {moveTypes} from './move-types';
import {baseTypes,basePools} from './catalog';
import {heroUrl} from './routes';
import './V2Workspace.css';
export type BetaHero={id:string;name:string;title:string;category:string;color:string;portrait:string|null;pool:string|null;schedule:string;month:string|null;notes:string;revision?:number;weapon_type?:string|null;move_type?:string|null;blessing?:string|null;demote?:boolean;heroic_grail?:boolean;debut_version?:string|null;release_date?:string|null;release_event?:string|null};
type Props<T extends BetaHero>={section:string;heroes:T[];onView:(hero:T)=>void;onRefresh:()=>Promise<void>};
const sections=[['My Watchlist','watchlist'],['Community','community'],['Administrative Manager','FEHRS_AdmManager/']] as const;
export function BetaNavigation(){return <aside className="beta-navigation"><p><strong>2.0 Beta · Head Admin testing</strong><span>Hero changes stay in the beta database. Other live editing is disabled.</span></p><nav aria-label="Version 2.0 beta tools">{sections.map(([label,path])=><a key={path} href={'/'+path}>{label}</a>)}</nav></aside>;}
const errorMessage=(e:unknown)=>e instanceof Error?e.message:'Could not complete the request.';
const title=(hero:BetaHero)=>hero.name+' — '+hero.title;
function HeroRows<T extends BetaHero>({heroes,onView}:{heroes:T[];onView:(h:T)=>void}){const [limit,setLimit]=useState(60);return <><ul className="v2-hero-list">{heroes.slice(0,limit).map(h=><li key={h.id}><button onClick={()=>onView(h)}>{h.portrait&&<img src={portraitUrl(h.portrait)} alt="" loading="lazy"/>}<span><strong>{h.name}</strong><small>{h.title}</small><small>{h.debut_version?'FEH '+h.debut_version:'Version not recorded'}</small></span></button></li>)}</ul>{heroes.length>limit&&<button className="secondary" onClick={()=>setLimit(v=>v+60)}>Show more</button>}{!heroes.length&&<p>No heroes match this selection.</p>}</>;}
export default function V2Workspace<T extends BetaHero>(p:Props<T>){
 const titleMap:Record<string,string>={'watchlist':'My Watchlist','community':'Community','bulk':'Bulk Edit Heroes','manage-versions':'Manage FEH Versions','beta-history':'Beta Change History'};
 return <section className="v2-workspace"><header className="fb-heading"><h2>{titleMap[p.section]||'Version 2.0'}</h2></header>{p.section==='watchlist'?<Watchlist {...p}/>:p.section==='bulk'?<BulkEditor {...p}/>:p.section==='manage-versions'?<VersionsManagement onRefresh={p.onRefresh}/>:p.section==='beta-history'?<BetaHistory/>:<Community/>}</section>;
}
type Follow={hero_id:string;list_name:string};
function Watchlist<T extends BetaHero>(p:Props<T>){const [view,setView]=useState<'grid'|'list'|'icons'>(()=>{try{const saved=localStorage.getItem('feh-beta-watchlist-view');return saved==='list'||saved==='icons'?saved:'grid';}catch{return 'grid';}});useEffect(()=>{try{localStorage.setItem('feh-beta-watchlist-view',view);}catch{}},[view]);const [follows,setFollows]=useState<Follow[]>([]),[query,setQuery]=useState(''),[list,setList]=useState('All'),[sort,setSort]=useState('rerun'),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;const load=()=>{void betaRequest('watchlist').then(rows=>{if(alive){setFollows(rows);setError('');}}).catch(e=>{if(alive)setError(errorMessage(e));}).finally(()=>{if(alive)setLoading(false);});};load();window.addEventListener('beta-watchlist-change',load);return()=>{alive=false;window.removeEventListener('beta-watchlist-change',load);};},[]);
 async function update(hero:T,listName:string,follow=true){setBusy(hero.id);setError('');try{await betaRequest('watchlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hero_id:hero.id,list_name:listName,follow})});setFollows(rows=>follow?rows.map(f=>f.hero_id===hero.id?{...f,list_name:listName}:f):rows.filter(f=>f.hero_id!==hero.id));window.dispatchEvent(new Event('beta-watchlist-change'));}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 const saved=p.heroes.filter(h=>follows.some(f=>f.hero_id===h.id)),rows=saved.filter(h=>(list==='All'||follows.find(f=>f.hero_id===h.id)?.list_name===list)&&title(h).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?title(a).localeCompare(title(b)):(a.month||'9999').localeCompare(b.month||'9999')||title(a).localeCompare(title(b)));
 return <><p>Add heroes from their profile using <strong>Add to my watchlist</strong>. Organize your saved heroes here and check their recorded reruns.</p><div className="v2-watch-summary"><strong>{saved.length} saved heroes</strong><span>{saved.filter(h=>h.month).length} with a recorded rerun</span><a className="secondary" href="/all-heroes">Browse heroes</a></div><div className="v2-toolbar"><label>Search my watchlist<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hero name or title"/></label><label>Collection<select value={list} onChange={e=>setList(e.target.value)}>{['All','Following','Saving for','Merge project','Waiting for rerun'].map(v=><option key={v}>{v}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="rerun">Next rerun</option><option value="name">Name · A–Z</option></select></label></div>{loading?<p role="status">Loading your watchlist…</p>:<><div className="v2-watch-display"><p role="status">{rows.length} of {saved.length} saved heroes</p><div className="v2-watch-view-switch" role="group" aria-label="Watchlist view">{(['grid','list','icons'] as const).map(mode=><button key={mode} type="button" className="secondary" aria-label={mode==='icons'?'Small icons view':mode==='list'?'List view':'Grid view'} title={mode==='icons'?'Small icons':mode==='list'?'List':'Grid'} aria-pressed={view===mode} onClick={()=>setView(mode)}>{mode==='grid'?<Grid2X2 size={20}/>:mode==='list'?<List size={20}/>:<LayoutGrid size={20}/>}</button>)}</div></div><ul className={'v2-watch-grid v2-watch-view-'+view}>{rows.map(h=><li key={h.id}><button className="v2-watch-hero" title={title(h)} onClick={()=>p.onView(h)}>{h.portrait?<img src={portraitUrl(h.portrait)} alt="" loading="lazy"/>:<span className="v2-watch-placeholder" aria-hidden="true"><Shield size={32}/></span>}<span><strong>{h.name}</strong><small>{h.title}</small><small>{h.month?'Next rerun · '+h.month.slice(0,7):h.schedule==='None'?'No rerun recorded':'Awaiting a rerun'}</small></span></button><details className="v2-watch-manage" open={view!=='icons'}><summary>Manage {h.name}</summary><div className="v2-watch-controls"><label>Collection for {h.name}<select value={follows.find(f=>f.hero_id===h.id)?.list_name||'Following'} disabled={!!busy} onChange={e=>void update(h,e.target.value)}>{['Following','Saving for','Merge project','Waiting for rerun'].map(v=><option key={v}>{v}</option>)}</select></label><button className="secondary" disabled={!!busy} onClick={()=>void update(h,'Following',false)}>{busy===h.id?'Saving…':'Remove'}</button></div></details></li>)}</ul>{!saved.length&&<div className="v2-watch-empty"><h3>Your watchlist starts with a hero</h3><p>Open a hero profile and choose Add to my watchlist.</p><a className="primary" href="/all-heroes">Find heroes</a></div>}{saved.length>0&&!rows.length&&<p>No saved heroes match these filters.</p>}</>}{error&&<p className="error" role="alert">{error}</p>}</>;
}export function BetaHistory(){const [rows,setRows]=useState<{id:string;label:string;created_at:string;before_json:string;after_json:string}[]>([]),[error,setError]=useState('');useEffect(()=>{void betaRequest('history').then(setRows).catch(e=>setError(errorMessage(e)));},[]);return <><p>Changes made to isolated beta hero records. This is an editing log, not historical rerun data.</p><ul className="v2-simple-list">{rows.map(r=><li key={r.id}><details><summary>{r.label} · {new Date(r.created_at).toLocaleString()}</summary><pre>{JSON.stringify({before:JSON.parse(r.before_json),after:JSON.parse(r.after_json)},null,2)}</pre></details></li>)}</ul>{!rows.length&&!error&&<p>No beta changes recorded.</p>}{error&&<p className="error" role="alert">{error}</p>}</>;}
type ArchiveBanner={id:string;name:string;starts_on:string;ends_on:string;banner_type:string;tracker_banner_heroes:{hero_id:string;slot_index:number|null}[]};
function Community(){return <><p>Discuss FEH, share rerun predictions, and suggest improvements through the project’s GitHub community. This private beta stages the community interface before opening the public forum.</p><div className="v2-archive-grid">{[['Discussions','https://github.com/clustifle/FEH-Rerun-Schedule-by-Clustifle','Open GitHub repository'],['Suggestions & corrections','https://github.com/clustifle/FEH-Rerun-Schedule-by-Clustifle/issues/new','Submit a suggestion or report incorrect information']].map(([name,url,label])=><article key={name}><h3>{name}</h3><a className="secondary" href={url} target="_blank" rel="noopener noreferrer">{label}</a></article>)}</div><p>GitHub Discussions is not enabled on the repository yet. Forum activation, the website feed, featured threads, and direct replies remain subsequent beta work. Predictions do not confirm a rerun.</p></>;}
export function V2HeroInfo({hero,heroes=[]}:{hero:BetaHero;heroes?:BetaHero[]}){
 const [banners,setBanners]=useState<ArchiveBanner[]>([]),[following,setFollowing]=useState(false),[watchReady,setWatchReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setBanners([]);setFollowing(false);setWatchReady(false);setError('');void apiFetch('/api/banners').then(async r=>{if(!r.ok)throw Error('Could not load banner appearances.');return r.json() as Promise<ArchiveBanner[]>;}).then(rows=>{if(alive)setBanners(rows.filter(b=>b.tracker_banner_heroes.some(s=>s.hero_id===hero.id)).sort((a,b)=>b.starts_on.localeCompare(a.starts_on)));}).catch(e=>{if(alive)setError(errorMessage(e));});void betaRequest('watchlist').then((follows:Follow[])=>{if(alive){setFollowing(follows.some(f=>f.hero_id===hero.id));setWatchReady(true);}}).catch(e=>{if(alive)setError(errorMessage(e));});return()=>{alive=false;};},[hero.id]);
 async function follow(){setBusy(true);setError('');try{await betaRequest('watchlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hero_id:hero.id,list_name:'Following',follow:!following})});setFollowing(!following);window.dispatchEvent(new Event('beta-watchlist-change'));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const variants=heroes.filter(h=>h.id!==hero.id&&h.name===hero.name),today=new Date().toISOString().slice(0,10);
 return <section className="v2-profile-info"><h3>FEH debut</h3><dl><div><dt>Version</dt><dd>{hero.debut_version?'FEH '+hero.debut_version:'Not recorded'}</dd></div><div><dt>Release date</dt><dd>{hero.release_date||'Not recorded'}</dd></div><div><dt>Original summon event</dt><dd>{hero.release_event||'Not recorded'}</dd></div></dl><div className="v2-actions"><button className="secondary" disabled={busy||!watchReady} aria-pressed={following} onClick={()=>void follow()}>{!watchReady?'Loading watchlist…':busy?'Saving…':following?'Remove from my watchlist':'Add to my watchlist'}</button><a className="secondary" href="/watchlist">My Watchlist</a></div><h3>Recorded banner appearances</h3>{banners.length?<ul className="v2-simple-list">{banners.map(b=><li key={b.id}><span><strong>{b.name}</strong><small>{b.starts_on} – {b.ends_on} · {b.ends_on<today?'Past event':b.starts_on>today?'Upcoming event':'Current event'}</small></span></li>)}</ul>:<p>No banner appearances recorded.</p>}<p>History includes only events stored on this website. Waitlist placements do not confirm future appearances.</p>{variants.length>0&&<><h3>Other variants</h3><div className="v2-actions">{variants.map(h=><a className="secondary" key={h.id} href={heroUrl(h,heroes)}>{h.title||h.category}</a>)}</div></>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
