import {useEffect,useRef,useState} from 'react';
import {Plus,Search,Pencil,Trash2,X,CalendarDays,Users,Layers} from 'lucide-react';
import {betaRequest} from './beta';
import {loadVersions,useVersions,type FehVersion} from './VersionSelect';
import './VersionsManagement.css';
const message=(e:unknown)=>e instanceof Error?e.message:'Could not update this version.';

export default function VersionsManagement({onRefresh}:{onRefresh:()=>Promise<void>}){
 const versions=useVersions(),dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null);
 const [original,setOriginal]=useState<string|null>(null),[version,setVersion]=useState(''),[date,setDate]=useState(''),[order,setOrder]=useState('1000'),[query,setQuery]=useState(''),[major,setMajor]=useState('All'),[usage,setUsage]=useState('All'),[deleting,setDeleting]=useState<FehVersion|null>(null),[replacement,setReplacement]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const editing=original!==null,rows=versions.filter(v=>(major==='All'||v.version.split('.')[0]===major)&&(usage==='All'||(usage==='Assigned'?(v.hero_count||0)>0:!v.hero_count))&&('v'+v.version+' '+(v.release_date||'')).toLowerCase().includes(query.trim().toLowerCase()));
 useEffect(()=>{void loadVersions().catch(e=>setError(message(e))).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(deleting){dialog.current?.showModal();}else dialog.current?.close();},[deleting]);
 function edit(v:FehVersion){setOriginal(v.version);setVersion(v.version);setDate(v.release_date||'');setOrder(String(v.sort_order));setError('');requestAnimationFrame(()=>input.current?.focus({preventScroll:true}));}
 function add(){const latest=[...versions].sort((a,b)=>{const x=a.version.split('.').map(Number),y=b.version.split('.').map(Number);return y[0]-x[0]||y[1]-x[1];})[0];const [m,n]=(latest?.version||'0.0').split('.').map(Number);setOriginal('');setVersion(latest?(n<99?m+'.'+(n+1):(m+1)+'.0'):'1.0');setDate('');setOrder(String(Math.min(100000,Math.max(0,...versions.map(v=>v.sort_order))+1)));setError('');requestAnimationFrame(()=>input.current?.focus());}
 function closeDelete(){if(busy)return;setDeleting(null);setError('');}
 async function change(method:'POST'|'DELETE',data:unknown){setBusy(true);setError('');try{await betaRequest('versions',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});setNotice(method==='DELETE'?'Version deleted. Hero assignments were updated.':'Version saved. Hero forms and filters are updated.');setOriginal(null);setDeleting(null);await loadVersions(true);await onRefresh();}catch(e){setError(message(e));}finally{setBusy(false);}}
 function save(e:React.FormEvent){e.preventDefault();if(!original&&versions.some(v=>v.version===version)){setError('This version already exists. Select it in the list to edit it.');return;}void change('POST',{version,original_version:original||undefined,release_date:date||null,sort_order:Number(order)});}
 return <div className="version-manager"><p>Choose a version to edit, or add the next FEH update. Renaming updates assigned heroes automatically.</p><div className="version-overview"><span><Layers size={20}/><strong>{versions.length}</strong> versions</span><span><Users size={20}/><strong>{versions.reduce((sum,v)=>sum+(v.hero_count||0),0)}</strong> assigned heroes</span><span><CalendarDays size={20}/><strong>{versions.filter(v=>v.release_date).length}</strong> release dates recorded</span></div><div className="version-manager-layout"><section className="version-list-panel"><header><h3>Versions</h3><button className="primary" disabled={busy} onClick={add}><Plus size={18}/>Add version</button></header><label className="version-search"><Search size={18}/><input type="search" aria-label="Find version" placeholder="Search v10.0 or a date" value={query} disabled={busy} onChange={e=>setQuery(e.target.value)}/></label><div className="version-filters"><label>Major version<select value={major} disabled={busy} onChange={e=>setMajor(e.target.value)}><option>All</option>{[...new Set(versions.map(v=>v.version.split('.')[0]))].map(v=><option key={v} value={v}>v{v}.x</option>)}</select></label><label>Hero assignments<select value={usage} disabled={busy} onChange={e=>setUsage(e.target.value)}><option>All</option><option>Assigned</option><option>Unused</option></select></label></div><p className="version-list-count" role="status">{rows.length} of {versions.length} versions</p>{loading?<p role="status">Loading versions…</p>:<ul className="version-records">{rows.map(v=><li key={v.version} className={original===v.version?'is-selected':''}><button className="version-record-select" disabled={busy} aria-label={'Edit v'+v.version} aria-pressed={original===v.version} onClick={()=>edit(v)}><strong>v{v.version}</strong><span>{v.release_date||'Date not recorded'}<small>{v.hero_count||0} heroes · Order {v.sort_order}</small></span><Pencil size={16}/></button><button className="version-delete-icon" disabled={busy} aria-label={'Delete v'+v.version} title={'Delete v'+v.version} onClick={()=>{setDeleting(v);setReplacement('');setError('');}}><Trash2 size={18}/></button></li>)}</ul>}{!loading&&!rows.length&&<p className="version-empty">No versions match these filters.</p>}</section>
 <section className="version-editor-panel" aria-label="Version editor">{editing?<form onSubmit={save}><header><h3>{original?'Edit v'+original:'Add version'}</h3><button type="button" className="version-close" aria-label="Close version editor" disabled={busy} onClick={()=>{setOriginal(null);setError('');}}><X size={20}/></button></header><label>Version number<div className="version-number-input"><span>v</span><input ref={input} aria-label="Version number" required pattern="[0-9]{1,2}[.](0|[1-9][0-9]?)" value={version} disabled={busy} onChange={e=>setVersion(e.target.value)} placeholder="10.1"/></div></label><small>Use the update number, such as 10.1.</small><label>Release date · optional<input type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><details className="version-advanced"><summary>Display order</summary><label>Order<input type="number" required min={0} max={100000} value={order} disabled={busy} onChange={e=>setOrder(e.target.value)}/></label><p>Lower numbers appear first in hero forms and filters.</p></details>{original&&version!==original&&<p className="version-impact">Renaming v{original} to v{version||'…'} updates {versions.find(v=>v.version===original)?.hero_count||0} assigned heroes.</p>}<div className="version-editor-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>{setOriginal(null);setError('');}}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':original?'Save changes':'Add version'}</button></div></form>:<div className="version-editor-empty"><Layers size={40}/><h3>Manage an update</h3><p>Select a version from the list to edit its number, release date or display order.</p><button className="secondary" disabled={busy} onClick={add}><Plus size={18}/>Add a new version</button></div>}{error&&!deleting&&<p className="error" role="alert">{error}</p>}</section></div>{notice&&<p className="version-notice" role="status">{notice}</p>}
 <dialog ref={dialog} className="version-delete-dialog" aria-labelledby="version-delete-title" onCancel={e=>{e.preventDefault();closeDelete();}} onClick={e=>{if(e.target===e.currentTarget)closeDelete();}}><header><h3 id="version-delete-title">Delete v{deleting?.version}?</h3><button className="version-close" aria-label="Close delete confirmation" disabled={busy} onClick={closeDelete}><X size={20}/></button></header><p>This removes the version from forms and filters. The {deleting?.hero_count||0} assigned heroes will remain.</p><label>Move assigned heroes to<select value={replacement} disabled={busy} onChange={e=>setReplacement(e.target.value)}><option value="">Not recorded · clear their version</option>{versions.filter(v=>v.version!==deleting?.version).map(v=><option key={v.version} value={v.version}>v{v.version}</option>)}</select></label><p className="version-impact">{replacement?'Assigned heroes will use v'+replacement+'.':'Assigned heroes will have no recorded debut version.'}</p>{error&&<p className="error" role="alert">{error}</p>}<div className="version-editor-actions"><button className="secondary" disabled={busy} onClick={closeDelete}>Cancel</button><button className="danger" disabled={busy} onClick={()=>void change('DELETE',{version:deleting?.version,replacement:replacement||null})}>{busy?'Deleting…':'Delete version'}</button></div></dialog></div>;
}
