import HeroPortraitMarks from './HeroPortraitMarks';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,ChevronsUp,ChevronsDown,Layers,X} from 'lucide-react';
import {portraitUrl,supabase} from './static-data';
type Hero={id:string;name:string;title:string;color:string;category?:string;blessing?:string|null;weapon_type?:string|null;move_type?:string|null;portrait:string|null};
export default function WaitlistReorganizer({heroes,onClose,onSaved}:{heroes:Hero[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const dialog=useRef<HTMLDialogElement>(null),[color,setColor]=useState('Red'),[rows,setRows]=useState(()=>heroes.filter(h=>h.color==='Red')),[selected,setSelected]=useState(''),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog.current?.close();document.body.style.overflow=overflow;};},[]);
 function changeColor(next:string){setColor(next);setRows(heroes.filter(h=>h.color===next));setSelected('');setDirty(false);setError('');setMessage('');}
 const index=rows.findIndex(h=>h.id===selected);
 function move(to:number){if(index<0||to<0||to>=rows.length||index===to)return;setRows(old=>{const next=[...old];next.splice(to,0,next.splice(index,1)[0]);return next;});setDirty(true);setMessage('');}
 async function save(){setSaving(true);setError('');try{const result=await supabase.rpc('reorder_tracker_waitlist',{weapon_color:color,ordered_ids:rows.map(h=>h.id)});if(result.error)throw result.error;await onSaved();setDirty(false);setMessage(color+' order saved.');}catch{setError('Could not save order. Ensure the waitlist ordering database update is installed, then try again. If the list changed, reopen this panel.');}finally{setSaving(false);}}
 return <dialog ref={dialog} className="waitlist-reorganizer" aria-labelledby="waitlist-order-title" onCancel={e=>{e.preventDefault();if(!saving)onClose();}}><header><div><h2 id="waitlist-order-title"><Layers size={22}/>Reorganize Waitlist</h2><p>Move heroes within their weapon color. First in the list appears first in its window.</p></div><button className="icon-button" aria-label="Close waitlist reorganizer" disabled={saving} onClick={onClose}><X/></button></header><div className="waitlist-order-colors" role="group" aria-label="Weapon color">{['Red','Blue','Green','Colorless'].map(c=><button key={c} className="secondary" aria-pressed={color===c} disabled={saving||(dirty&&color!==c)} onClick={()=>changeColor(c)}>{c}</button>)}</div><div className="waitlist-order-tools"><span>{rows.length} heroes</span><div>{[{icon:ChevronsUp,label:'Move to first',to:0},{icon:ArrowUp,label:'Move up',to:index-1},{icon:ArrowDown,label:'Move down',to:index+1},{icon:ChevronsDown,label:'Move to last',to:rows.length-1}].map(({icon:Icon,label,to})=><button key={label} className="icon-button" title={label} aria-label={label} disabled={saving||index<0||to<0||to>=rows.length||to===index} onClick={()=>move(to)}><Icon size={19}/></button>)}</div></div><ol className="waitlist-order-list" aria-label={color+' hero order'}>{rows.map((h,i)=><li key={h.id}><button aria-pressed={selected===h.id} disabled={saving} onClick={()=>setSelected(h.id)} onKeyDown={e=>{if(e.altKey&&(e.key==='ArrowUp'||e.key==='ArrowDown')){e.preventDefault();if(selected===h.id)move(index+(e.key==='ArrowUp'?-1:1));}}}><span className="waitlist-order-number">{i+1}</span><span className={'waitlist-order-portrait '+color.toLowerCase()}>{h.portrait?<img src={portraitUrl(h.portrait)} alt="" loading="lazy" decoding="async"/>:h.name[0]}<HeroPortraitMarks hero={h}/></span><span><strong>{h.name}</strong><small>{h.title}</small></span></button></li>)}</ol>{!rows.length&&<p className="waitlist-order-empty">No {color.toLowerCase()} heroes in Waitlist.</p>}<footer><p role={error?'alert':'status'}>{error||message||(dirty?'Unsaved changes · save or discard before switching color.':'Select a hero, then use the move buttons. Alt + ↑ / ↓ also moves the selected hero.')}</p><div><button className="secondary" disabled={saving||!dirty} onClick={()=>changeColor(color)}>Discard changes</button><button className="primary" disabled={saving||!dirty} onClick={()=>void save()}>{saving?'Saving…':'Save order'}</button></div></footer></dialog>;
}
